# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Bulk operations
#' @description olrundeck.Bulk
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ job_bulk_delete } \emph{ Delete multiple job definitions at once }
#' 
#'
#' \itemize{
#' \item \emph{ @param } inline_object1 \link{InlineObject1}
#' \item \emph{ @returnType } \link{JobBulkOperationResponse} \cr
#'
#'
#' \item status code : 200 | Job deleted response
#'
#' \item return type : JobBulkOperationResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  job_bulk_delete  ####################
#'
#' library(olrundeck)
#' var.inline_object1 <- InlineObject1$new() # InlineObject1 | 
#'
#' #Delete multiple job definitions at once
#' api.instance <- BulkApi$new()
#'
#' #Configure API key authorization: rundeck_auth
#' api.instance$apiClient$apiKeys['X-Rundeck-Auth-Token'] <- 'TODO_YOUR_API_KEY';
#'
#' result <- api.instance$job_bulk_delete(var.inline_object1)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
BulkApi <- R6::R6Class(
  'BulkApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    job_bulk_delete = function(inline_object1, ...){
      apiResponse <- self$job_bulk_deleteWithHttpInfo(inline_object1, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    job_bulk_deleteWithHttpInfo = function(inline_object1, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`inline_object1`)) {
        stop("Missing required parameter `inline_object1`.")
      }

      if (!missing(`inline_object1`)) {
        body <- sprintf(
        '
          %s
        ',
            jsonlite::toJSON(`inline_object1`$toJSON(), auto_unbox=TRUE, digits = NA)
        )
      } else {
        body <- NULL
      }

      urlPath <- "/api/26/jobs/delete"
      # API key authentication
      if ("X-Rundeck-Auth-Token" %in% names(self$apiClient$apiKeys) && nchar(self$apiClient$apiKeys["X-Rundeck-Auth-Token"]) > 0) {
        headerParams['X-Rundeck-Auth-Token'] <- paste(unlist(self$apiClient$apiKeys["X-Rundeck-Auth-Token"]), collapse='')
      }

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "JobBulkOperationResponse", loadNamespace("olrundeck")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
