# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Cluster operations
#' @description olrundeck.Cluster
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ system_scheduled_jobs_for_server } \emph{ List the scheduled Jobs with their schedule owned by the cluster server with the specified UUID }
#' 
#'
#' \itemize{
#' \item \emph{ @param } uuid character
#' \item \emph{ @returnType } list( \link{Job} ) \cr
#'
#'
#' \item status code : 200 | Expected response to a valid request
#'
#' \item return type : array[Job] 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ system_scheduled_jobs_list } \emph{ List the scheduled Jobs with their schedule owned by the cluster server }
#' 
#'
#' \itemize{
#' \item \emph{ @returnType } list( \link{Job} ) \cr
#'
#'
#' \item status code : 200 | Expected response to a valid request
#'
#' \item return type : array[Job] 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ system_scheduler_takeover } \emph{ Tell a Rundeck server in cluster mode to claim all scheduled jobs from another cluster server }
#' 
#'
#' \itemize{
#' \item \emph{ @param } inline_object10 \link{InlineObject10}
#' \item \emph{ @returnType } \link{TakeoverScheduleResponse} \cr
#'
#'
#' \item status code : 200 | Expected response to a valid request
#'
#' \item return type : TakeoverScheduleResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  system_scheduled_jobs_for_server  ####################
#'
#' library(olrundeck)
#' var.uuid <- 'uuid_example' # character | The ID of the user to retrieve profile information for
#'
#' #List the scheduled Jobs with their schedule owned by the cluster server with the specified UUID
#' api.instance <- ClusterApi$new()
#'
#' #Configure API key authorization: rundeck_auth
#' api.instance$apiClient$apiKeys['X-Rundeck-Auth-Token'] <- 'TODO_YOUR_API_KEY';
#'
#' result <- api.instance$system_scheduled_jobs_for_server(var.uuid)
#'
#'
#' ####################  system_scheduled_jobs_list  ####################
#'
#' library(olrundeck)
#'
#' #List the scheduled Jobs with their schedule owned by the cluster server
#' api.instance <- ClusterApi$new()
#'
#' #Configure API key authorization: rundeck_auth
#' api.instance$apiClient$apiKeys['X-Rundeck-Auth-Token'] <- 'TODO_YOUR_API_KEY';
#'
#' result <- api.instance$system_scheduled_jobs_list()
#'
#'
#' ####################  system_scheduler_takeover  ####################
#'
#' library(olrundeck)
#' var.inline_object10 <- InlineObject10$new() # InlineObject10 | 
#'
#' #Tell a Rundeck server in cluster mode to claim all scheduled jobs from another cluster server
#' api.instance <- ClusterApi$new()
#'
#' #Configure API key authorization: rundeck_auth
#' api.instance$apiClient$apiKeys['X-Rundeck-Auth-Token'] <- 'TODO_YOUR_API_KEY';
#'
#' result <- api.instance$system_scheduler_takeover(var.inline_object10)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
ClusterApi <- R6::R6Class(
  'ClusterApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    system_scheduled_jobs_for_server = function(uuid, ...){
      apiResponse <- self$system_scheduled_jobs_for_serverWithHttpInfo(uuid, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    system_scheduled_jobs_for_serverWithHttpInfo = function(uuid, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`uuid`)) {
        stop("Missing required parameter `uuid`.")
      }

      urlPath <- "/api/26/scheduler/server/{uuid}/jobs"
      if (!missing(`uuid`)) {
        urlPath <- gsub(paste0("\\{", "uuid", "\\}"), URLencode(as.character(`uuid`), reserved = TRUE), urlPath)
      }

      # API key authentication
      if ("X-Rundeck-Auth-Token" %in% names(self$apiClient$apiKeys) && nchar(self$apiClient$apiKeys["X-Rundeck-Auth-Token"]) > 0) {
        headerParams['X-Rundeck-Auth-Token'] <- paste(unlist(self$apiClient$apiKeys["X-Rundeck-Auth-Token"]), collapse='')
      }

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "array[Job]", loadNamespace("olrundeck")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    system_scheduled_jobs_list = function(...){
      apiResponse <- self$system_scheduled_jobs_listWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    system_scheduled_jobs_listWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      urlPath <- "/api/26/scheduler/jobs"
      # API key authentication
      if ("X-Rundeck-Auth-Token" %in% names(self$apiClient$apiKeys) && nchar(self$apiClient$apiKeys["X-Rundeck-Auth-Token"]) > 0) {
        headerParams['X-Rundeck-Auth-Token'] <- paste(unlist(self$apiClient$apiKeys["X-Rundeck-Auth-Token"]), collapse='')
      }

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "array[Job]", loadNamespace("olrundeck")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    system_scheduler_takeover = function(inline_object10, ...){
      apiResponse <- self$system_scheduler_takeoverWithHttpInfo(inline_object10, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    system_scheduler_takeoverWithHttpInfo = function(inline_object10, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`inline_object10`)) {
        stop("Missing required parameter `inline_object10`.")
      }

      if (!missing(`inline_object10`)) {
        body <- sprintf(
        '
          %s
        ',
            jsonlite::toJSON(`inline_object10`$toJSON(), auto_unbox=TRUE, digits = NA)
        )
      } else {
        body <- NULL
      }

      urlPath <- "/api/26/scheduler/takeover"
      # API key authentication
      if ("X-Rundeck-Auth-Token" %in% names(self$apiClient$apiKeys) && nchar(self$apiClient$apiKeys["X-Rundeck-Auth-Token"]) > 0) {
        headerParams['X-Rundeck-Auth-Token'] <- paste(unlist(self$apiClient$apiKeys["X-Rundeck-Auth-Token"]), collapse='')
      }

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "PUT",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "TakeoverScheduleResponse", loadNamespace("olrundeck")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
