# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ExecutionList
#' @description ExecutionList Class
#' @format An \code{R6Class} generator object
#' @field paging  \link{Paging} [optional]
#'
#' @field executions  list( \link{Execution} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ExecutionList <- R6::R6Class(
  'ExecutionList',
  public = list(
    `paging` = NULL,
    `executions` = NULL,
    initialize = function(`paging`=NULL, `executions`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`paging`)) {
        stopifnot(R6::is.R6(`paging`))
        self$`paging` <- `paging`
      }
      if (!is.null(`executions`)) {
        stopifnot(is.vector(`executions`))
        sapply(`executions`, function(x) stopifnot(R6::is.R6(x)))
        self$`executions` <- `executions`
      }
    },
    toJSON = function() {
      ExecutionListObject <- list()
      if (!is.null(self$`paging`)) {
        ExecutionListObject[['paging']] <-
          self$`paging`$toJSON()
      }
      if (!is.null(self$`executions`)) {
        ExecutionListObject[['executions']] <-
          lapply(self$`executions`, function(x) x$toJSON())
      }

      ExecutionListObject
    },
    fromJSON = function(ExecutionListJson) {
      ExecutionListObject <- jsonlite::fromJSON(ExecutionListJson)
      if (!is.null(ExecutionListObject$`paging`)) {
        pagingObject <- Paging$new()
        pagingObject$fromJSON(jsonlite::toJSON(ExecutionListObject$paging, auto_unbox = TRUE, digits = NA))
        self$`paging` <- pagingObject
      }
      if (!is.null(ExecutionListObject$`executions`)) {
        self$`executions` <- ApiClient$new()$deserializeObj(ExecutionListObject$`executions`, "array[Execution]", loadNamespace("openlattice_rundeck"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`paging`)) {
        sprintf(
        '"paging":
        %s
        ',
        jsonlite::toJSON(self$`paging`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`executions`)) {
        sprintf(
        '"executions":
        [%s]
',
        paste(sapply(self$`executions`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ExecutionListJson) {
      ExecutionListObject <- jsonlite::fromJSON(ExecutionListJson)
      self$`paging` <- Paging$new()$fromJSON(jsonlite::toJSON(ExecutionListObject$paging, auto_unbox = TRUE, digits = NA))
      self$`executions` <- ApiClient$new()$deserializeObj(ExecutionListObject$`executions`, "array[Execution]", loadNamespace("openlattice_rundeck"))
      self
    }
  )
)
