# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ExecutionOutputEntry
#' @description ExecutionOutputEntry Class
#' @format An \code{R6Class} generator object
#' @field time  character [optional]
#'
#' @field absolute_time  character [optional]
#'
#' @field log  character [optional]
#'
#' @field level  character [optional]
#'
#' @field stepctx  character [optional]
#'
#' @field node  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ExecutionOutputEntry <- R6::R6Class(
  'ExecutionOutputEntry',
  public = list(
    `time` = NULL,
    `absolute_time` = NULL,
    `log` = NULL,
    `level` = NULL,
    `stepctx` = NULL,
    `node` = NULL,
    initialize = function(`time`=NULL, `absolute_time`=NULL, `log`=NULL, `level`=NULL, `stepctx`=NULL, `node`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`time`)) {
        stopifnot(is.character(`time`), length(`time`) == 1)
        self$`time` <- `time`
      }
      if (!is.null(`absolute_time`)) {
        stopifnot(is.character(`absolute_time`), length(`absolute_time`) == 1)
        self$`absolute_time` <- `absolute_time`
      }
      if (!is.null(`log`)) {
        stopifnot(is.character(`log`), length(`log`) == 1)
        self$`log` <- `log`
      }
      if (!is.null(`level`)) {
        stopifnot(is.character(`level`), length(`level`) == 1)
        self$`level` <- `level`
      }
      if (!is.null(`stepctx`)) {
        stopifnot(is.character(`stepctx`), length(`stepctx`) == 1)
        self$`stepctx` <- `stepctx`
      }
      if (!is.null(`node`)) {
        stopifnot(is.character(`node`), length(`node`) == 1)
        self$`node` <- `node`
      }
    },
    toJSON = function() {
      ExecutionOutputEntryObject <- list()
      if (!is.null(self$`time`)) {
        ExecutionOutputEntryObject[['time']] <-
          self$`time`
      }
      if (!is.null(self$`absolute_time`)) {
        ExecutionOutputEntryObject[['absolute_time']] <-
          self$`absolute_time`
      }
      if (!is.null(self$`log`)) {
        ExecutionOutputEntryObject[['log']] <-
          self$`log`
      }
      if (!is.null(self$`level`)) {
        ExecutionOutputEntryObject[['level']] <-
          self$`level`
      }
      if (!is.null(self$`stepctx`)) {
        ExecutionOutputEntryObject[['stepctx']] <-
          self$`stepctx`
      }
      if (!is.null(self$`node`)) {
        ExecutionOutputEntryObject[['node']] <-
          self$`node`
      }

      ExecutionOutputEntryObject
    },
    fromJSON = function(ExecutionOutputEntryJson) {
      ExecutionOutputEntryObject <- jsonlite::fromJSON(ExecutionOutputEntryJson)
      if (!is.null(ExecutionOutputEntryObject$`time`)) {
        self$`time` <- ExecutionOutputEntryObject$`time`
      }
      if (!is.null(ExecutionOutputEntryObject$`absolute_time`)) {
        self$`absolute_time` <- ExecutionOutputEntryObject$`absolute_time`
      }
      if (!is.null(ExecutionOutputEntryObject$`log`)) {
        self$`log` <- ExecutionOutputEntryObject$`log`
      }
      if (!is.null(ExecutionOutputEntryObject$`level`)) {
        self$`level` <- ExecutionOutputEntryObject$`level`
      }
      if (!is.null(ExecutionOutputEntryObject$`stepctx`)) {
        self$`stepctx` <- ExecutionOutputEntryObject$`stepctx`
      }
      if (!is.null(ExecutionOutputEntryObject$`node`)) {
        self$`node` <- ExecutionOutputEntryObject$`node`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`time`)) {
        sprintf(
        '"time":
          "%s"
                ',
        self$`time`
        )},
        if (!is.null(self$`absolute_time`)) {
        sprintf(
        '"absolute_time":
          "%s"
                ',
        self$`absolute_time`
        )},
        if (!is.null(self$`log`)) {
        sprintf(
        '"log":
          "%s"
                ',
        self$`log`
        )},
        if (!is.null(self$`level`)) {
        sprintf(
        '"level":
          "%s"
                ',
        self$`level`
        )},
        if (!is.null(self$`stepctx`)) {
        sprintf(
        '"stepctx":
          "%s"
                ',
        self$`stepctx`
        )},
        if (!is.null(self$`node`)) {
        sprintf(
        '"node":
          "%s"
                ',
        self$`node`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ExecutionOutputEntryJson) {
      ExecutionOutputEntryObject <- jsonlite::fromJSON(ExecutionOutputEntryJson)
      self$`time` <- ExecutionOutputEntryObject$`time`
      self$`absolute_time` <- ExecutionOutputEntryObject$`absolute_time`
      self$`log` <- ExecutionOutputEntryObject$`log`
      self$`level` <- ExecutionOutputEntryObject$`level`
      self$`stepctx` <- ExecutionOutputEntryObject$`stepctx`
      self$`node` <- ExecutionOutputEntryObject$`node`
      self
    }
  )
)
