# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Execution
#' @description Execution Class
#' @format An \code{R6Class} generator object
#' @field id  numeric [optional]
#'
#' @field href  character [optional]
#'
#' @field permalink  character [optional]
#'
#' @field status  character [optional]
#'
#' @field customStatus  character [optional]
#'
#' @field project  character [optional]
#'
#' @field user  character [optional]
#'
#' @field serverUUID  character [optional]
#'
#' @field date-started  object [optional]
#'
#' @field job  \link{JobMetadata} [optional]
#'
#' @field description  character [optional]
#'
#' @field argstring  character [optional]
#'
#' @field successfulNodes  list( character ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Execution <- R6::R6Class(
  'Execution',
  public = list(
    `id` = NULL,
    `href` = NULL,
    `permalink` = NULL,
    `status` = NULL,
    `customStatus` = NULL,
    `project` = NULL,
    `user` = NULL,
    `serverUUID` = NULL,
    `date-started` = NULL,
    `job` = NULL,
    `description` = NULL,
    `argstring` = NULL,
    `successfulNodes` = NULL,
    initialize = function(`id`=NULL, `href`=NULL, `permalink`=NULL, `status`=NULL, `customStatus`=NULL, `project`=NULL, `user`=NULL, `serverUUID`=NULL, `date-started`=NULL, `job`=NULL, `description`=NULL, `argstring`=NULL, `successfulNodes`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        self$`id` <- `id`
      }
      if (!is.null(`href`)) {
        stopifnot(is.character(`href`), length(`href`) == 1)
        self$`href` <- `href`
      }
      if (!is.null(`permalink`)) {
        stopifnot(is.character(`permalink`), length(`permalink`) == 1)
        self$`permalink` <- `permalink`
      }
      if (!is.null(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!is.null(`customStatus`)) {
        stopifnot(is.character(`customStatus`), length(`customStatus`) == 1)
        self$`customStatus` <- `customStatus`
      }
      if (!is.null(`project`)) {
        stopifnot(is.character(`project`), length(`project`) == 1)
        self$`project` <- `project`
      }
      if (!is.null(`user`)) {
        stopifnot(is.character(`user`), length(`user`) == 1)
        self$`user` <- `user`
      }
      if (!is.null(`serverUUID`)) {
        stopifnot(is.character(`serverUUID`), length(`serverUUID`) == 1)
        self$`serverUUID` <- `serverUUID`
      }
      if (!is.null(`date-started`)) {
        self$`date-started` <- `date-started`
      }
      if (!is.null(`job`)) {
        stopifnot(R6::is.R6(`job`))
        self$`job` <- `job`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`argstring`)) {
        stopifnot(is.character(`argstring`), length(`argstring`) == 1)
        self$`argstring` <- `argstring`
      }
      if (!is.null(`successfulNodes`)) {
        stopifnot(is.vector(`successfulNodes`))
        sapply(`successfulNodes`, function(x) stopifnot(is.character(x)))
        self$`successfulNodes` <- `successfulNodes`
      }
    },
    toJSON = function() {
      ExecutionObject <- list()
      if (!is.null(self$`id`)) {
        ExecutionObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`href`)) {
        ExecutionObject[['href']] <-
          self$`href`
      }
      if (!is.null(self$`permalink`)) {
        ExecutionObject[['permalink']] <-
          self$`permalink`
      }
      if (!is.null(self$`status`)) {
        ExecutionObject[['status']] <-
          self$`status`
      }
      if (!is.null(self$`customStatus`)) {
        ExecutionObject[['customStatus']] <-
          self$`customStatus`
      }
      if (!is.null(self$`project`)) {
        ExecutionObject[['project']] <-
          self$`project`
      }
      if (!is.null(self$`user`)) {
        ExecutionObject[['user']] <-
          self$`user`
      }
      if (!is.null(self$`serverUUID`)) {
        ExecutionObject[['serverUUID']] <-
          self$`serverUUID`
      }
      if (!is.null(self$`date-started`)) {
        ExecutionObject[['date-started']] <-
          self$`date-started`
      }
      if (!is.null(self$`job`)) {
        ExecutionObject[['job']] <-
          self$`job`$toJSON()
      }
      if (!is.null(self$`description`)) {
        ExecutionObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`argstring`)) {
        ExecutionObject[['argstring']] <-
          self$`argstring`
      }
      if (!is.null(self$`successfulNodes`)) {
        ExecutionObject[['successfulNodes']] <-
          self$`successfulNodes`
      }

      ExecutionObject
    },
    fromJSON = function(ExecutionJson) {
      ExecutionObject <- jsonlite::fromJSON(ExecutionJson)
      if (!is.null(ExecutionObject$`id`)) {
        self$`id` <- ExecutionObject$`id`
      }
      if (!is.null(ExecutionObject$`href`)) {
        self$`href` <- ExecutionObject$`href`
      }
      if (!is.null(ExecutionObject$`permalink`)) {
        self$`permalink` <- ExecutionObject$`permalink`
      }
      if (!is.null(ExecutionObject$`status`)) {
        self$`status` <- ExecutionObject$`status`
      }
      if (!is.null(ExecutionObject$`customStatus`)) {
        self$`customStatus` <- ExecutionObject$`customStatus`
      }
      if (!is.null(ExecutionObject$`project`)) {
        self$`project` <- ExecutionObject$`project`
      }
      if (!is.null(ExecutionObject$`user`)) {
        self$`user` <- ExecutionObject$`user`
      }
      if (!is.null(ExecutionObject$`serverUUID`)) {
        self$`serverUUID` <- ExecutionObject$`serverUUID`
      }
      if (!is.null(ExecutionObject$`date-started`)) {
        self$`date-started` <- ExecutionObject$`date-started`
      }
      if (!is.null(ExecutionObject$`job`)) {
        jobObject <- JobMetadata$new()
        jobObject$fromJSON(jsonlite::toJSON(ExecutionObject$job, auto_unbox = TRUE, digits = NA))
        self$`job` <- jobObject
      }
      if (!is.null(ExecutionObject$`description`)) {
        self$`description` <- ExecutionObject$`description`
      }
      if (!is.null(ExecutionObject$`argstring`)) {
        self$`argstring` <- ExecutionObject$`argstring`
      }
      if (!is.null(ExecutionObject$`successfulNodes`)) {
        self$`successfulNodes` <- ApiClient$new()$deserializeObj(ExecutionObject$`successfulNodes`, "array[character]", loadNamespace("openlattice-rundeck"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`href`)) {
        sprintf(
        '"href":
          "%s"
                ',
        self$`href`
        )},
        if (!is.null(self$`permalink`)) {
        sprintf(
        '"permalink":
          "%s"
                ',
        self$`permalink`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          "%s"
                ',
        self$`status`
        )},
        if (!is.null(self$`customStatus`)) {
        sprintf(
        '"customStatus":
          "%s"
                ',
        self$`customStatus`
        )},
        if (!is.null(self$`project`)) {
        sprintf(
        '"project":
          "%s"
                ',
        self$`project`
        )},
        if (!is.null(self$`user`)) {
        sprintf(
        '"user":
          "%s"
                ',
        self$`user`
        )},
        if (!is.null(self$`serverUUID`)) {
        sprintf(
        '"serverUUID":
          "%s"
                ',
        self$`serverUUID`
        )},
        if (!is.null(self$`date-started`)) {
        sprintf(
        '"date-started":
          "%s"
                ',
        self$`date-started`
        )},
        if (!is.null(self$`job`)) {
        sprintf(
        '"job":
        %s
        ',
        jsonlite::toJSON(self$`job`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`argstring`)) {
        sprintf(
        '"argstring":
          "%s"
                ',
        self$`argstring`
        )},
        if (!is.null(self$`successfulNodes`)) {
        sprintf(
        '"successfulNodes":
           [%s]
        ',
        paste(unlist(lapply(self$`successfulNodes`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ExecutionJson) {
      ExecutionObject <- jsonlite::fromJSON(ExecutionJson)
      self$`id` <- ExecutionObject$`id`
      self$`href` <- ExecutionObject$`href`
      self$`permalink` <- ExecutionObject$`permalink`
      self$`status` <- ExecutionObject$`status`
      self$`customStatus` <- ExecutionObject$`customStatus`
      self$`project` <- ExecutionObject$`project`
      self$`user` <- ExecutionObject$`user`
      self$`serverUUID` <- ExecutionObject$`serverUUID`
      self$`date-started` <- ExecutionObject$`date-started`
      self$`job` <- JobMetadata$new()$fromJSON(jsonlite::toJSON(ExecutionObject$job, auto_unbox = TRUE, digits = NA))
      self$`description` <- ExecutionObject$`description`
      self$`argstring` <- ExecutionObject$`argstring`
      self$`successfulNodes` <- ApiClient$new()$deserializeObj(ExecutionObject$`successfulNodes`, "array[character]", loadNamespace("openlattice-rundeck"))
      self
    }
  )
)
