# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title File operations
#' @description openlattice-rundeck.File
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ api26_execution_id_output_get } \emph{ List input files for an execution }
#' 
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } offset character
#' \item \emph{ @param } maxlines \link{AnyType}
#'
#'
#' \item status code : 200 | List of execution input files
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  api26_execution_id_output_get  ####################
#'
#' library(openlattice-rundeck)
#' var.id <- 'id_example' # character | 
#' var.offset <- 'offset_example' # character | 
#' var.maxlines <- AnyType$new() # AnyType | 
#'
#' #List input files for an execution
#' api.instance <- FileApi$new()
#'
#' result <- api.instance$api26_execution_id_output_get(var.id, offset=var.offset, maxlines=var.maxlines)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
FileApi <- R6::R6Class(
  'FileApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    api26_execution_id_output_get = function(id, offset=NULL, maxlines=NULL, ...){
      apiResponse <- self$api26_execution_id_output_getWithHttpInfo(id, offset, maxlines, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    api26_execution_id_output_getWithHttpInfo = function(id, offset=NULL, maxlines=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      queryParams['offset'] <- offset

      queryParams['maxlines'] <- maxlines

      urlPath <- "/api/26/execution/{id}/output"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
