# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title IncompleteLogExecution
#' @description IncompleteLogExecution Class
#' @format An \code{R6Class} generator object
#' @field id  character [optional]
#'
#' @field project  character [optional]
#'
#' @field href  character [optional]
#'
#' @field permalink  character [optional]
#'
#' @field storage  object [optional]
#'
#' @field errors  list( character ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
IncompleteLogExecution <- R6::R6Class(
  'IncompleteLogExecution',
  public = list(
    `id` = NULL,
    `project` = NULL,
    `href` = NULL,
    `permalink` = NULL,
    `storage` = NULL,
    `errors` = NULL,
    initialize = function(`id`=NULL, `project`=NULL, `href`=NULL, `permalink`=NULL, `storage`=NULL, `errors`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`project`)) {
        stopifnot(is.character(`project`), length(`project`) == 1)
        self$`project` <- `project`
      }
      if (!is.null(`href`)) {
        stopifnot(is.character(`href`), length(`href`) == 1)
        self$`href` <- `href`
      }
      if (!is.null(`permalink`)) {
        stopifnot(is.character(`permalink`), length(`permalink`) == 1)
        self$`permalink` <- `permalink`
      }
      if (!is.null(`storage`)) {
        self$`storage` <- `storage`
      }
      if (!is.null(`errors`)) {
        stopifnot(is.vector(`errors`))
        sapply(`errors`, function(x) stopifnot(is.character(x)))
        self$`errors` <- `errors`
      }
    },
    toJSON = function() {
      IncompleteLogExecutionObject <- list()
      if (!is.null(self$`id`)) {
        IncompleteLogExecutionObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`project`)) {
        IncompleteLogExecutionObject[['project']] <-
          self$`project`
      }
      if (!is.null(self$`href`)) {
        IncompleteLogExecutionObject[['href']] <-
          self$`href`
      }
      if (!is.null(self$`permalink`)) {
        IncompleteLogExecutionObject[['permalink']] <-
          self$`permalink`
      }
      if (!is.null(self$`storage`)) {
        IncompleteLogExecutionObject[['storage']] <-
          self$`storage`
      }
      if (!is.null(self$`errors`)) {
        IncompleteLogExecutionObject[['errors']] <-
          self$`errors`
      }

      IncompleteLogExecutionObject
    },
    fromJSON = function(IncompleteLogExecutionJson) {
      IncompleteLogExecutionObject <- jsonlite::fromJSON(IncompleteLogExecutionJson)
      if (!is.null(IncompleteLogExecutionObject$`id`)) {
        self$`id` <- IncompleteLogExecutionObject$`id`
      }
      if (!is.null(IncompleteLogExecutionObject$`project`)) {
        self$`project` <- IncompleteLogExecutionObject$`project`
      }
      if (!is.null(IncompleteLogExecutionObject$`href`)) {
        self$`href` <- IncompleteLogExecutionObject$`href`
      }
      if (!is.null(IncompleteLogExecutionObject$`permalink`)) {
        self$`permalink` <- IncompleteLogExecutionObject$`permalink`
      }
      if (!is.null(IncompleteLogExecutionObject$`storage`)) {
        self$`storage` <- IncompleteLogExecutionObject$`storage`
      }
      if (!is.null(IncompleteLogExecutionObject$`errors`)) {
        self$`errors` <- ApiClient$new()$deserializeObj(IncompleteLogExecutionObject$`errors`, "array[character]", loadNamespace("openlattice-rundeck"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`project`)) {
        sprintf(
        '"project":
          "%s"
                ',
        self$`project`
        )},
        if (!is.null(self$`href`)) {
        sprintf(
        '"href":
          "%s"
                ',
        self$`href`
        )},
        if (!is.null(self$`permalink`)) {
        sprintf(
        '"permalink":
          "%s"
                ',
        self$`permalink`
        )},
        if (!is.null(self$`storage`)) {
        sprintf(
        '"storage":
          "%s"
                ',
        self$`storage`
        )},
        if (!is.null(self$`errors`)) {
        sprintf(
        '"errors":
           [%s]
        ',
        paste(unlist(lapply(self$`errors`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(IncompleteLogExecutionJson) {
      IncompleteLogExecutionObject <- jsonlite::fromJSON(IncompleteLogExecutionJson)
      self$`id` <- IncompleteLogExecutionObject$`id`
      self$`project` <- IncompleteLogExecutionObject$`project`
      self$`href` <- IncompleteLogExecutionObject$`href`
      self$`permalink` <- IncompleteLogExecutionObject$`permalink`
      self$`storage` <- IncompleteLogExecutionObject$`storage`
      self$`errors` <- ApiClient$new()$deserializeObj(IncompleteLogExecutionObject$`errors`, "array[character]", loadNamespace("openlattice-rundeck"))
      self
    }
  )
)
