# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineResponse2001
#' @description InlineResponse2001 Class
#' @format An \code{R6Class} generator object
#' @field _links  \link{InlineResponse2001Links} 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2001 <- R6::R6Class(
  'InlineResponse2001',
  public = list(
    `_links` = NULL,
    initialize = function(`_links`, ...){
      local.optional.var <- list(...)
      if (!missing(`_links`)) {
        stopifnot(R6::is.R6(`_links`))
        self$`_links` <- `_links`
      }
    },
    toJSON = function() {
      InlineResponse2001Object <- list()
      if (!is.null(self$`_links`)) {
        InlineResponse2001Object[['_links']] <-
          self$`_links`$toJSON()
      }

      InlineResponse2001Object
    },
    fromJSON = function(InlineResponse2001Json) {
      InlineResponse2001Object <- jsonlite::fromJSON(InlineResponse2001Json)
      if (!is.null(InlineResponse2001Object$`_links`)) {
        _linksObject <- InlineResponse2001Links$new()
        _linksObject$fromJSON(jsonlite::toJSON(InlineResponse2001Object$_links, auto_unbox = TRUE, digits = NA))
        self$`_links` <- _linksObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`_links`)) {
        sprintf(
        '"_links":
        %s
        ',
        jsonlite::toJSON(self$`_links`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineResponse2001Json) {
      InlineResponse2001Object <- jsonlite::fromJSON(InlineResponse2001Json)
      self$`_links` <- InlineResponse2001Links$new()$fromJSON(jsonlite::toJSON(InlineResponse2001Object$_links, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
