# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineObject1
#' @description InlineObject1 Class
#' @format An \code{R6Class} generator object
#' @field value  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineObject1 <- R6::R6Class(
  'InlineObject1',
  public = list(
    `value` = NULL,
    initialize = function(`value`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`value`)) {
        stopifnot(is.character(`value`), length(`value`) == 1)
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      InlineObject1Object <- list()
      if (!is.null(self$`value`)) {
        InlineObject1Object[['value']] <-
          self$`value`
      }

      InlineObject1Object
    },
    fromJSON = function(InlineObject1Json) {
      InlineObject1Object <- jsonlite::fromJSON(InlineObject1Json)
      if (!is.null(InlineObject1Object$`value`)) {
        self$`value` <- InlineObject1Object$`value`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
          "%s"
                ',
        self$`value`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineObject1Json) {
      InlineObject1Object <- jsonlite::fromJSON(InlineObject1Json)
      self$`value` <- InlineObject1Object$`value`
      self
    }
  )
)
