# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineObject8
#' @description InlineObject8 Class
#' @format An \code{R6Class} generator object
#' @field contents  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineObject8 <- R6::R6Class(
  'InlineObject8',
  public = list(
    `contents` = NULL,
    initialize = function(`contents`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`contents`)) {
        stopifnot(is.character(`contents`), length(`contents`) == 1)
        self$`contents` <- `contents`
      }
    },
    toJSON = function() {
      InlineObject8Object <- list()
      if (!is.null(self$`contents`)) {
        InlineObject8Object[['contents']] <-
          self$`contents`
      }

      InlineObject8Object
    },
    fromJSON = function(InlineObject8Json) {
      InlineObject8Object <- jsonlite::fromJSON(InlineObject8Json)
      if (!is.null(InlineObject8Object$`contents`)) {
        self$`contents` <- InlineObject8Object$`contents`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`contents`)) {
        sprintf(
        '"contents":
          "%s"
                ',
        self$`contents`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineObject8Json) {
      InlineObject8Object <- jsonlite::fromJSON(InlineObject8Json)
      self$`contents` <- InlineObject8Object$`contents`
      self
    }
  )
)
