# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InlineObject3
#' @description InlineObject3 Class
#' @format An \code{R6Class} generator object
#' @field ids  list( character ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineObject3 <- R6::R6Class(
  'InlineObject3',
  public = list(
    `ids` = NULL,
    initialize = function(`ids`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`ids`)) {
        stopifnot(is.vector(`ids`))
        sapply(`ids`, function(x) stopifnot(is.character(x)))
        self$`ids` <- `ids`
      }
    },
    toJSON = function() {
      InlineObject3Object <- list()
      if (!is.null(self$`ids`)) {
        InlineObject3Object[['ids']] <-
          self$`ids`
      }

      InlineObject3Object
    },
    fromJSON = function(InlineObject3Json) {
      InlineObject3Object <- jsonlite::fromJSON(InlineObject3Json)
      if (!is.null(InlineObject3Object$`ids`)) {
        self$`ids` <- ApiClient$new()$deserializeObj(InlineObject3Object$`ids`, "array[character]", loadNamespace("openlattice_rundeck"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`ids`)) {
        sprintf(
        '"ids":
           [%s]
        ',
        paste(unlist(lapply(self$`ids`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InlineObject3Json) {
      InlineObject3Object <- jsonlite::fromJSON(InlineObject3Json)
      self$`ids` <- ApiClient$new()$deserializeObj(InlineObject3Object$`ids`, "array[character]", loadNamespace("openlattice_rundeck"))
      self
    }
  )
)
