# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InvalidAclPolicyResponse
#' @description InvalidAclPolicyResponse Class
#' @format An \code{R6Class} generator object
#' @field valid  character [optional]
#'
#' @field policies  list( \link{InvalidAclPolicyResponsePolicies} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InvalidAclPolicyResponse <- R6::R6Class(
  'InvalidAclPolicyResponse',
  public = list(
    `valid` = NULL,
    `policies` = NULL,
    initialize = function(`valid`=NULL, `policies`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`valid`)) {
        self$`valid` <- `valid`
      }
      if (!is.null(`policies`)) {
        stopifnot(is.vector(`policies`))
        sapply(`policies`, function(x) stopifnot(R6::is.R6(x)))
        self$`policies` <- `policies`
      }
    },
    toJSON = function() {
      InvalidAclPolicyResponseObject <- list()
      if (!is.null(self$`valid`)) {
        InvalidAclPolicyResponseObject[['valid']] <-
          self$`valid`
      }
      if (!is.null(self$`policies`)) {
        InvalidAclPolicyResponseObject[['policies']] <-
          lapply(self$`policies`, function(x) x$toJSON())
      }

      InvalidAclPolicyResponseObject
    },
    fromJSON = function(InvalidAclPolicyResponseJson) {
      InvalidAclPolicyResponseObject <- jsonlite::fromJSON(InvalidAclPolicyResponseJson)
      if (!is.null(InvalidAclPolicyResponseObject$`valid`)) {
        self$`valid` <- InvalidAclPolicyResponseObject$`valid`
      }
      if (!is.null(InvalidAclPolicyResponseObject$`policies`)) {
        self$`policies` <- ApiClient$new()$deserializeObj(InvalidAclPolicyResponseObject$`policies`, "array[InvalidAclPolicyResponsePolicies]", loadNamespace("openlattice-rundeck"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`valid`)) {
        sprintf(
        '"valid":
          "%s"
                ',
        self$`valid`
        )},
        if (!is.null(self$`policies`)) {
        sprintf(
        '"policies":
        [%s]
',
        paste(sapply(self$`policies`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InvalidAclPolicyResponseJson) {
      InvalidAclPolicyResponseObject <- jsonlite::fromJSON(InvalidAclPolicyResponseJson)
      self$`valid` <- InvalidAclPolicyResponseObject$`valid`
      self$`policies` <- ApiClient$new()$deserializeObj(InvalidAclPolicyResponseObject$`policies`, "array[InvalidAclPolicyResponsePolicies]", loadNamespace("openlattice-rundeck"))
      self
    }
  )
)
