# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title InvalidAclPolicyResponsePolicies
#' @description InvalidAclPolicyResponsePolicies Class
#' @format An \code{R6Class} generator object
#' @field policy  character [optional]
#'
#' @field errors  list( character ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InvalidAclPolicyResponsePolicies <- R6::R6Class(
  'InvalidAclPolicyResponsePolicies',
  public = list(
    `policy` = NULL,
    `errors` = NULL,
    initialize = function(`policy`=NULL, `errors`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`policy`)) {
        stopifnot(is.character(`policy`), length(`policy`) == 1)
        self$`policy` <- `policy`
      }
      if (!is.null(`errors`)) {
        stopifnot(is.vector(`errors`))
        sapply(`errors`, function(x) stopifnot(is.character(x)))
        self$`errors` <- `errors`
      }
    },
    toJSON = function() {
      InvalidAclPolicyResponsePoliciesObject <- list()
      if (!is.null(self$`policy`)) {
        InvalidAclPolicyResponsePoliciesObject[['policy']] <-
          self$`policy`
      }
      if (!is.null(self$`errors`)) {
        InvalidAclPolicyResponsePoliciesObject[['errors']] <-
          self$`errors`
      }

      InvalidAclPolicyResponsePoliciesObject
    },
    fromJSON = function(InvalidAclPolicyResponsePoliciesJson) {
      InvalidAclPolicyResponsePoliciesObject <- jsonlite::fromJSON(InvalidAclPolicyResponsePoliciesJson)
      if (!is.null(InvalidAclPolicyResponsePoliciesObject$`policy`)) {
        self$`policy` <- InvalidAclPolicyResponsePoliciesObject$`policy`
      }
      if (!is.null(InvalidAclPolicyResponsePoliciesObject$`errors`)) {
        self$`errors` <- ApiClient$new()$deserializeObj(InvalidAclPolicyResponsePoliciesObject$`errors`, "array[character]", loadNamespace("openlattice_rundeck"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`policy`)) {
        sprintf(
        '"policy":
          "%s"
                ',
        self$`policy`
        )},
        if (!is.null(self$`errors`)) {
        sprintf(
        '"errors":
           [%s]
        ',
        paste(unlist(lapply(self$`errors`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(InvalidAclPolicyResponsePoliciesJson) {
      InvalidAclPolicyResponsePoliciesObject <- jsonlite::fromJSON(InvalidAclPolicyResponsePoliciesJson)
      self$`policy` <- InvalidAclPolicyResponsePoliciesObject$`policy`
      self$`errors` <- ApiClient$new()$deserializeObj(InvalidAclPolicyResponsePoliciesObject$`errors`, "array[character]", loadNamespace("openlattice_rundeck"))
      self
    }
  )
)
