# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title JobBulkOperationResponse
#' @description JobBulkOperationResponse Class
#' @format An \code{R6Class} generator object
#' @field requestCount  numeric 
#'
#' @field allsuccessful  character 
#'
#' @field succeeded  list( \link{BulkJobSucceededInfo} ) [optional]
#'
#' @field failed  list( \link{BulkJobFailedInfo} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
JobBulkOperationResponse <- R6::R6Class(
  'JobBulkOperationResponse',
  public = list(
    `requestCount` = NULL,
    `allsuccessful` = NULL,
    `succeeded` = NULL,
    `failed` = NULL,
    initialize = function(`requestCount`, `allsuccessful`, `succeeded`=NULL, `failed`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`requestCount`)) {
        self$`requestCount` <- `requestCount`
      }
      if (!missing(`allsuccessful`)) {
        self$`allsuccessful` <- `allsuccessful`
      }
      if (!is.null(`succeeded`)) {
        stopifnot(is.vector(`succeeded`))
        sapply(`succeeded`, function(x) stopifnot(R6::is.R6(x)))
        self$`succeeded` <- `succeeded`
      }
      if (!is.null(`failed`)) {
        stopifnot(is.vector(`failed`))
        sapply(`failed`, function(x) stopifnot(R6::is.R6(x)))
        self$`failed` <- `failed`
      }
    },
    toJSON = function() {
      JobBulkOperationResponseObject <- list()
      if (!is.null(self$`requestCount`)) {
        JobBulkOperationResponseObject[['requestCount']] <-
          self$`requestCount`
      }
      if (!is.null(self$`allsuccessful`)) {
        JobBulkOperationResponseObject[['allsuccessful']] <-
          self$`allsuccessful`
      }
      if (!is.null(self$`succeeded`)) {
        JobBulkOperationResponseObject[['succeeded']] <-
          lapply(self$`succeeded`, function(x) x$toJSON())
      }
      if (!is.null(self$`failed`)) {
        JobBulkOperationResponseObject[['failed']] <-
          lapply(self$`failed`, function(x) x$toJSON())
      }

      JobBulkOperationResponseObject
    },
    fromJSON = function(JobBulkOperationResponseJson) {
      JobBulkOperationResponseObject <- jsonlite::fromJSON(JobBulkOperationResponseJson)
      if (!is.null(JobBulkOperationResponseObject$`requestCount`)) {
        self$`requestCount` <- JobBulkOperationResponseObject$`requestCount`
      }
      if (!is.null(JobBulkOperationResponseObject$`allsuccessful`)) {
        self$`allsuccessful` <- JobBulkOperationResponseObject$`allsuccessful`
      }
      if (!is.null(JobBulkOperationResponseObject$`succeeded`)) {
        self$`succeeded` <- ApiClient$new()$deserializeObj(JobBulkOperationResponseObject$`succeeded`, "array[BulkJobSucceededInfo]", loadNamespace("olrundeck"))
      }
      if (!is.null(JobBulkOperationResponseObject$`failed`)) {
        self$`failed` <- ApiClient$new()$deserializeObj(JobBulkOperationResponseObject$`failed`, "array[BulkJobFailedInfo]", loadNamespace("olrundeck"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`requestCount`)) {
        sprintf(
        '"requestCount":
          %d
                ',
        self$`requestCount`
        )},
        if (!is.null(self$`allsuccessful`)) {
        sprintf(
        '"allsuccessful":
          "%s"
                ',
        self$`allsuccessful`
        )},
        if (!is.null(self$`succeeded`)) {
        sprintf(
        '"succeeded":
        [%s]
',
        paste(sapply(self$`succeeded`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`failed`)) {
        sprintf(
        '"failed":
        [%s]
',
        paste(sapply(self$`failed`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(JobBulkOperationResponseJson) {
      JobBulkOperationResponseObject <- jsonlite::fromJSON(JobBulkOperationResponseJson)
      self$`requestCount` <- JobBulkOperationResponseObject$`requestCount`
      self$`allsuccessful` <- JobBulkOperationResponseObject$`allsuccessful`
      self$`succeeded` <- ApiClient$new()$deserializeObj(JobBulkOperationResponseObject$`succeeded`, "array[BulkJobSucceededInfo]", loadNamespace("olrundeck"))
      self$`failed` <- ApiClient$new()$deserializeObj(JobBulkOperationResponseObject$`failed`, "array[BulkJobFailedInfo]", loadNamespace("olrundeck"))
      self
    }
  )
)
