# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title JobReference
#' @description JobReference Class
#' @format An \code{R6Class} generator object
#' @field href  character [optional]
#'
#' @field permalink  character [optional]
#'
#' @field id  character [optional]
#'
#' @field pervious-owner  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
JobReference <- R6::R6Class(
  'JobReference',
  public = list(
    `href` = NULL,
    `permalink` = NULL,
    `id` = NULL,
    `pervious-owner` = NULL,
    initialize = function(`href`=NULL, `permalink`=NULL, `id`=NULL, `pervious-owner`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`href`)) {
        stopifnot(is.character(`href`), length(`href`) == 1)
        self$`href` <- `href`
      }
      if (!is.null(`permalink`)) {
        stopifnot(is.character(`permalink`), length(`permalink`) == 1)
        self$`permalink` <- `permalink`
      }
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`pervious-owner`)) {
        stopifnot(is.character(`pervious-owner`), length(`pervious-owner`) == 1)
        self$`pervious-owner` <- `pervious-owner`
      }
    },
    toJSON = function() {
      JobReferenceObject <- list()
      if (!is.null(self$`href`)) {
        JobReferenceObject[['href']] <-
          self$`href`
      }
      if (!is.null(self$`permalink`)) {
        JobReferenceObject[['permalink']] <-
          self$`permalink`
      }
      if (!is.null(self$`id`)) {
        JobReferenceObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`pervious-owner`)) {
        JobReferenceObject[['pervious-owner']] <-
          self$`pervious-owner`
      }

      JobReferenceObject
    },
    fromJSON = function(JobReferenceJson) {
      JobReferenceObject <- jsonlite::fromJSON(JobReferenceJson)
      if (!is.null(JobReferenceObject$`href`)) {
        self$`href` <- JobReferenceObject$`href`
      }
      if (!is.null(JobReferenceObject$`permalink`)) {
        self$`permalink` <- JobReferenceObject$`permalink`
      }
      if (!is.null(JobReferenceObject$`id`)) {
        self$`id` <- JobReferenceObject$`id`
      }
      if (!is.null(JobReferenceObject$`pervious-owner`)) {
        self$`pervious-owner` <- JobReferenceObject$`pervious-owner`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`href`)) {
        sprintf(
        '"href":
          "%s"
                ',
        self$`href`
        )},
        if (!is.null(self$`permalink`)) {
        sprintf(
        '"permalink":
          "%s"
                ',
        self$`permalink`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`pervious-owner`)) {
        sprintf(
        '"pervious-owner":
          "%s"
                ',
        self$`pervious-owner`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(JobReferenceJson) {
      JobReferenceObject <- jsonlite::fromJSON(JobReferenceJson)
      self$`href` <- JobReferenceObject$`href`
      self$`permalink` <- JobReferenceObject$`permalink`
      self$`id` <- JobReferenceObject$`id`
      self$`pervious-owner` <- JobReferenceObject$`pervious-owner`
      self
    }
  )
)
