# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Project operations
#' @description openlattice-rundeck.Project
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ project_archive_export_sync } \emph{ Export archive of project synchronously }
#' 
#'
#' \itemize{
#' \item \emph{ @param } project character
#' \item \emph{ @param } execution_ids character
#' \item \emph{ @param } export_all \link{AnyType}
#' \item \emph{ @param } export_jobs character
#' \item \emph{ @param } export_executions character
#' \item \emph{ @param } export_configs character
#' \item \emph{ @param } export_readmes character
#' \item \emph{ @param } export_acls character
#'
#'
#' \item status code : 200 | Zip archive
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ project_archive_import } \emph{ Import project archive. }
#' 
#'
#' \itemize{
#' \item \emph{ @param } project character
#' \item \emph{ @param } body object
#' \item \emph{ @param } job_uuid_option \link{AnyType}
#' \item \emph{ @param } import_executions character
#' \item \emph{ @param } import_config character
#' \item \emph{ @param } import_acl character
#'
#'
#' \item status code : 200 | Expected response to a valid request
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ project_config_key_delete } \emph{ Delete project config key }
#' 
#'
#' \itemize{
#' \item \emph{ @param } project character
#' \item \emph{ @param } key character
#'
#'
#' \item status code : 200 | Success !
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ project_config_update } \emph{ Update project config }
#' 
#'
#' \itemize{
#' \item \emph{ @param } project character
#' \item \emph{ @param } body object
#'
#'
#' \item status code : 200 | Project config updated
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ project_create } \emph{ Create a new project }
#' 
#'
#' \itemize{
#' \item \emph{ @param } project_create_request \link{AnyType}
#'
#'
#' \item status code : 200 | Success !
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ project_delete } \emph{ Delete project }
#' 
#'
#' \itemize{
#' \item \emph{ @param } project character
#'
#'
#' \item status code : 200 | Success !
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ project_jobs_export } \emph{ Export the job definitions in XML or YAML formats. }
#' 
#'
#' \itemize{
#' \item \emph{ @param } project character
#' \item \emph{ @param } format \link{AnyType}
#' \item \emph{ @param } idlist character
#' \item \emph{ @param } group_path character
#' \item \emph{ @param } job_filter character
#'
#'
#' \item status code : 200 | Expected response to a valid request.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ project_jobs_import } \emph{ Import job definitions in XML or YAML formats. }
#' 
#'
#' \itemize{
#' \item \emph{ @param } project character
#' \item \emph{ @param } body object
#' \item \emph{ @param } content_type \link{AnyType}
#' \item \emph{ @param } accept \link{AnyType}
#' \item \emph{ @param } file_format \link{AnyType}
#' \item \emph{ @param } dupe_option \link{AnyType}
#' \item \emph{ @param } uuid_option \link{AnyType}
#'
#'
#' \item status code : 200 | Expected response to a valid request.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ project_motd_delete } \emph{ Delete project motd.md }
#' 
#'
#' \itemize{
#' \item \emph{ @param } project character
#'
#'
#' \item status code : 200 | Success !
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ project_readme_delete } \emph{ Delete project README.md }
#' 
#'
#' \itemize{
#' \item \emph{ @param } project character
#'
#'
#' \item status code : 200 | Success !
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  project_archive_export_sync  ####################
#'
#' library(openlattice-rundeck)
#' var.project <- 'project_example' # character | Name of the project to import jobs into.
#' var.execution_ids <- 'execution_ids_example' # character | A list (comma-separated) of execution IDs. If this is specified then the archive will contain only executions that are specified, and will not contain Jobs, ACLs, or project configuration/readme files.
#' var.export_all <- AnyType$new() # AnyType | Export all project resources
#' var.export_jobs <- 'export_jobs_example' # character | Export all project resources
#' var.export_executions <- 'export_executions_example' # character | Export all project resources
#' var.export_configs <- 'export_configs_example' # character | Export all project resources
#' var.export_readmes <- 'export_readmes_example' # character | Export all project resources
#' var.export_acls <- 'export_acls_example' # character | Export all project resources
#'
#' #Export archive of project synchronously
#' api.instance <- ProjectApi$new()
#'
#' result <- api.instance$project_archive_export_sync(var.project, execution_ids=var.execution_ids, export_all=var.export_all, export_jobs=var.export_jobs, export_executions=var.export_executions, export_configs=var.export_configs, export_readmes=var.export_readmes, export_acls=var.export_acls)
#'
#'
#' ####################  project_archive_import  ####################
#'
#' library(openlattice-rundeck)
#' var.project <- 'project_example' # character | Name of the project to import jobs into.
#' var.body <- NULL # object | 
#' var.job_uuid_option <- AnyType$new() # AnyType | 
#' var.import_executions <- 'import_executions_example' # character | 
#' var.import_config <- 'import_config_example' # character | 
#' var.import_acl <- 'import_acl_example' # character | 
#'
#' #Import project archive.
#' api.instance <- ProjectApi$new()
#'
#' result <- api.instance$project_archive_import(var.project, var.body, job_uuid_option=var.job_uuid_option, import_executions=var.import_executions, import_config=var.import_config, import_acl=var.import_acl)
#'
#'
#' ####################  project_config_key_delete  ####################
#'
#' library(openlattice-rundeck)
#' var.project <- 'project_example' # character | 
#' var.key <- 'key_example' # character | 
#'
#' #Delete project config key
#' api.instance <- ProjectApi$new()
#'
#' result <- api.instance$project_config_key_delete(var.project, var.key)
#'
#'
#' ####################  project_config_update  ####################
#'
#' library(openlattice-rundeck)
#' var.project <- 'project_example' # character | 
#' var.body <- NULL # object | 
#'
#' #Update project config
#' api.instance <- ProjectApi$new()
#'
#' result <- api.instance$project_config_update(var.project, var.body)
#'
#'
#' ####################  project_create  ####################
#'
#' library(openlattice-rundeck)
#' var.project_create_request <- AnyType$new() # AnyType | 
#'
#' #Create a new project
#' api.instance <- ProjectApi$new()
#'
#' result <- api.instance$project_create(var.project_create_request)
#'
#'
#' ####################  project_delete  ####################
#'
#' library(openlattice-rundeck)
#' var.project <- 'project_example' # character | 
#'
#' #Delete project
#' api.instance <- ProjectApi$new()
#'
#' result <- api.instance$project_delete(var.project)
#'
#'
#' ####################  project_jobs_export  ####################
#'
#' library(openlattice-rundeck)
#' var.project <- 'project_example' # character | The project to export jobs for.
#' var.format <- AnyType$new() # AnyType | XML or YAML format for exported jobs.
#' var.idlist <- 'idlist_example' # character | A comma-separated list of Job IDs to export.
#' var.group_path <- 'group_path_example' # character | Group or partial group path to include all jobs within that group path.
#' var.job_filter <- 'job_filter_example' # character | Filter for the job Name.
#'
#' #Export the job definitions in XML or YAML formats.
#' api.instance <- ProjectApi$new()
#'
#' result <- api.instance$project_jobs_export(var.project, format=var.format, idlist=var.idlist, group_path=var.group_path, job_filter=var.job_filter)
#'
#'
#' ####################  project_jobs_import  ####################
#'
#' library(openlattice-rundeck)
#' var.project <- 'project_example' # character | Name of the project to import jobs into.
#' var.body <- NULL # object | 
#' var.content_type <- AnyType$new() # AnyType | 
#' var.accept <- AnyType$new() # AnyType | 
#' var.file_format <- AnyType$new() # AnyType | 
#' var.dupe_option <- AnyType$new() # AnyType | 
#' var.uuid_option <- AnyType$new() # AnyType | 
#'
#' #Import job definitions in XML or YAML formats.
#' api.instance <- ProjectApi$new()
#'
#' result <- api.instance$project_jobs_import(var.project, var.body, content_type=var.content_type, accept=var.accept, file_format=var.file_format, dupe_option=var.dupe_option, uuid_option=var.uuid_option)
#'
#'
#' ####################  project_motd_delete  ####################
#'
#' library(openlattice-rundeck)
#' var.project <- 'project_example' # character | Name of the project to import jobs into.
#'
#' #Delete project motd.md
#' api.instance <- ProjectApi$new()
#'
#' result <- api.instance$project_motd_delete(var.project)
#'
#'
#' ####################  project_readme_delete  ####################
#'
#' library(openlattice-rundeck)
#' var.project <- 'project_example' # character | Name of the project to import jobs into.
#'
#' #Delete project README.md
#' api.instance <- ProjectApi$new()
#'
#' result <- api.instance$project_readme_delete(var.project)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
ProjectApi <- R6::R6Class(
  'ProjectApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    project_archive_export_sync = function(project, execution_ids=NULL, export_all=NULL, export_jobs=NULL, export_executions=NULL, export_configs=NULL, export_readmes=NULL, export_acls=NULL, ...){
      apiResponse <- self$project_archive_export_syncWithHttpInfo(project, execution_ids, export_all, export_jobs, export_executions, export_configs, export_readmes, export_acls, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    project_archive_export_syncWithHttpInfo = function(project, execution_ids=NULL, export_all=NULL, export_jobs=NULL, export_executions=NULL, export_configs=NULL, export_readmes=NULL, export_acls=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`project`)) {
        stop("Missing required parameter `project`.")
      }

      queryParams['executionIds'] <- execution_ids

      queryParams['exportAll'] <- export_all

      queryParams['exportJobs'] <- export_jobs

      queryParams['exportExecutions'] <- export_executions

      queryParams['exportConfigs'] <- export_configs

      queryParams['exportReadmes'] <- export_readmes

      queryParams['exportAcls'] <- export_acls

      urlPath <- "/api/26/project/{project}/export"
      if (!missing(`project`)) {
        urlPath <- gsub(paste0("\\{", "project", "\\}"), URLencode(as.character(`project`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    project_archive_import = function(project, body, job_uuid_option=NULL, import_executions=NULL, import_config=NULL, import_acl=NULL, ...){
      apiResponse <- self$project_archive_importWithHttpInfo(project, body, job_uuid_option, import_executions, import_config, import_acl, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    project_archive_importWithHttpInfo = function(project, body, job_uuid_option=NULL, import_executions=NULL, import_config=NULL, import_acl=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`project`)) {
        stop("Missing required parameter `project`.")
      }

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      queryParams['jobUuidOption'] <- job_uuid_option

      queryParams['importExecutions'] <- import_executions

      queryParams['importConfig'] <- import_config

      queryParams['importACL'] <- import_acl

      if (!missing(`body`)) {
        body <- sprintf(
        '
            "%s"
                  ',
            `body`
        )
      } else {
        body <- NULL
      }

      urlPath <- "/api/26/project/{project}/import"
      if (!missing(`project`)) {
        urlPath <- gsub(paste0("\\{", "project", "\\}"), URLencode(as.character(`project`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "PUT",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    project_config_key_delete = function(project, key, ...){
      apiResponse <- self$project_config_key_deleteWithHttpInfo(project, key, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    project_config_key_deleteWithHttpInfo = function(project, key, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`project`)) {
        stop("Missing required parameter `project`.")
      }

      if (missing(`key`)) {
        stop("Missing required parameter `key`.")
      }

      urlPath <- "/api/26/project/{project}/config/{key}"
      if (!missing(`project`)) {
        urlPath <- gsub(paste0("\\{", "project", "\\}"), URLencode(as.character(`project`), reserved = TRUE), urlPath)
      }

      if (!missing(`key`)) {
        urlPath <- gsub(paste0("\\{", "key", "\\}"), URLencode(as.character(`key`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    project_config_update = function(project, body, ...){
      apiResponse <- self$project_config_updateWithHttpInfo(project, body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    project_config_updateWithHttpInfo = function(project, body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`project`)) {
        stop("Missing required parameter `project`.")
      }

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- sprintf(
        '
            "%s"
                  ',
            `body`
        )
      } else {
        body <- NULL
      }

      urlPath <- "/api/26/project/{project}/config"
      if (!missing(`project`)) {
        urlPath <- gsub(paste0("\\{", "project", "\\}"), URLencode(as.character(`project`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "PUT",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    project_create = function(project_create_request, ...){
      apiResponse <- self$project_createWithHttpInfo(project_create_request, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    project_createWithHttpInfo = function(project_create_request, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`project_create_request`)) {
        stop("Missing required parameter `project_create_request`.")
      }

      urlPath <- "/api/26/projects"
      if (!missing(`project_create_request`)) {
        urlPath <- gsub(paste0("\\{", "ProjectCreateRequest", "\\}"), URLencode(as.character(`project_create_request`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    project_delete = function(project, ...){
      apiResponse <- self$project_deleteWithHttpInfo(project, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    project_deleteWithHttpInfo = function(project, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`project`)) {
        stop("Missing required parameter `project`.")
      }

      urlPath <- "/api/26/project/{project}"
      if (!missing(`project`)) {
        urlPath <- gsub(paste0("\\{", "project", "\\}"), URLencode(as.character(`project`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    project_jobs_export = function(project, format=NULL, idlist=NULL, group_path=NULL, job_filter=NULL, ...){
      apiResponse <- self$project_jobs_exportWithHttpInfo(project, format, idlist, group_path, job_filter, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    project_jobs_exportWithHttpInfo = function(project, format=NULL, idlist=NULL, group_path=NULL, job_filter=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`project`)) {
        stop("Missing required parameter `project`.")
      }

      queryParams['format'] <- format

      queryParams['idlist'] <- idlist

      queryParams['groupPath'] <- group_path

      queryParams['jobFilter'] <- job_filter

      urlPath <- "/api/26/project/{project}/jobs/export"
      if (!missing(`project`)) {
        urlPath <- gsub(paste0("\\{", "project", "\\}"), URLencode(as.character(`project`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    project_jobs_import = function(project, body, content_type=NULL, accept=NULL, file_format=NULL, dupe_option=NULL, uuid_option=NULL, ...){
      apiResponse <- self$project_jobs_importWithHttpInfo(project, body, content_type, accept, file_format, dupe_option, uuid_option, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    project_jobs_importWithHttpInfo = function(project, body, content_type=NULL, accept=NULL, file_format=NULL, dupe_option=NULL, uuid_option=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`project`)) {
        stop("Missing required parameter `project`.")
      }

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      headerParams['content-type'] <- `content_type`

      headerParams['accept'] <- `accept`

      queryParams['fileFormat'] <- file_format

      queryParams['dupeOption'] <- dupe_option

      queryParams['uuidOption'] <- uuid_option

      if (!missing(`body`)) {
        body <- sprintf(
        '
            "%s"
                  ',
            `body`
        )
      } else {
        body <- NULL
      }

      urlPath <- "/api/26/project/{project}/jobs/import"
      if (!missing(`project`)) {
        urlPath <- gsub(paste0("\\{", "project", "\\}"), URLencode(as.character(`project`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    project_motd_delete = function(project, ...){
      apiResponse <- self$project_motd_deleteWithHttpInfo(project, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    project_motd_deleteWithHttpInfo = function(project, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`project`)) {
        stop("Missing required parameter `project`.")
      }

      urlPath <- "/api/26/project/{project}/motd.md"
      if (!missing(`project`)) {
        urlPath <- gsub(paste0("\\{", "project", "\\}"), URLencode(as.character(`project`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    project_readme_delete = function(project, ...){
      apiResponse <- self$project_readme_deleteWithHttpInfo(project, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    project_readme_deleteWithHttpInfo = function(project, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`project`)) {
        stop("Missing required parameter `project`.")
      }

      urlPath <- "/api/26/project/{project}/readme.md"
      if (!missing(`project`)) {
        urlPath <- gsub(paste0("\\{", "project", "\\}"), URLencode(as.character(`project`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
