# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title RetryExecutionRequest
#' @description RetryExecutionRequest Class
#' @format An \code{R6Class} generator object
#' @field argString  character [optional]
#'
#' @field loglevel  character [optional]
#'
#' @field asUser  character [optional]
#'
#' @field options  object [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RetryExecutionRequest <- R6::R6Class(
  'RetryExecutionRequest',
  public = list(
    `argString` = NULL,
    `loglevel` = NULL,
    `asUser` = NULL,
    `options` = NULL,
    initialize = function(`argString`=NULL, `loglevel`=NULL, `asUser`=NULL, `options`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`argString`)) {
        stopifnot(is.character(`argString`), length(`argString`) == 1)
        self$`argString` <- `argString`
      }
      if (!is.null(`loglevel`)) {
        stopifnot(is.character(`loglevel`), length(`loglevel`) == 1)
        self$`loglevel` <- `loglevel`
      }
      if (!is.null(`asUser`)) {
        stopifnot(is.character(`asUser`), length(`asUser`) == 1)
        self$`asUser` <- `asUser`
      }
      if (!is.null(`options`)) {
        self$`options` <- `options`
      }
    },
    toJSON = function() {
      RetryExecutionRequestObject <- list()
      if (!is.null(self$`argString`)) {
        RetryExecutionRequestObject[['argString']] <-
          self$`argString`
      }
      if (!is.null(self$`loglevel`)) {
        RetryExecutionRequestObject[['loglevel']] <-
          self$`loglevel`
      }
      if (!is.null(self$`asUser`)) {
        RetryExecutionRequestObject[['asUser']] <-
          self$`asUser`
      }
      if (!is.null(self$`options`)) {
        RetryExecutionRequestObject[['options']] <-
          self$`options`
      }

      RetryExecutionRequestObject
    },
    fromJSON = function(RetryExecutionRequestJson) {
      RetryExecutionRequestObject <- jsonlite::fromJSON(RetryExecutionRequestJson)
      if (!is.null(RetryExecutionRequestObject$`argString`)) {
        self$`argString` <- RetryExecutionRequestObject$`argString`
      }
      if (!is.null(RetryExecutionRequestObject$`loglevel`)) {
        self$`loglevel` <- RetryExecutionRequestObject$`loglevel`
      }
      if (!is.null(RetryExecutionRequestObject$`asUser`)) {
        self$`asUser` <- RetryExecutionRequestObject$`asUser`
      }
      if (!is.null(RetryExecutionRequestObject$`options`)) {
        self$`options` <- RetryExecutionRequestObject$`options`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`argString`)) {
        sprintf(
        '"argString":
          "%s"
                ',
        self$`argString`
        )},
        if (!is.null(self$`loglevel`)) {
        sprintf(
        '"loglevel":
          "%s"
                ',
        self$`loglevel`
        )},
        if (!is.null(self$`asUser`)) {
        sprintf(
        '"asUser":
          "%s"
                ',
        self$`asUser`
        )},
        if (!is.null(self$`options`)) {
        sprintf(
        '"options":
          "%s"
                ',
        self$`options`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(RetryExecutionRequestJson) {
      RetryExecutionRequestObject <- jsonlite::fromJSON(RetryExecutionRequestJson)
      self$`argString` <- RetryExecutionRequestObject$`argString`
      self$`loglevel` <- RetryExecutionRequestObject$`loglevel`
      self$`asUser` <- RetryExecutionRequestObject$`asUser`
      self$`options` <- RetryExecutionRequestObject$`options`
      self
    }
  )
)
