# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StorageKeyMetadata
#' @description StorageKeyMetadata Class
#' @format An \code{R6Class} generator object
#' @field meta  object [optional]
#'
#' @field url  character [optional]
#'
#' @field name  character [optional]
#'
#' @field type  character [optional]
#'
#' @field path  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StorageKeyMetadata <- R6::R6Class(
  'StorageKeyMetadata',
  public = list(
    `meta` = NULL,
    `url` = NULL,
    `name` = NULL,
    `type` = NULL,
    `path` = NULL,
    initialize = function(`meta`=NULL, `url`=NULL, `name`=NULL, `type`=NULL, `path`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`meta`)) {
        self$`meta` <- `meta`
      }
      if (!is.null(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
        self$`url` <- `url`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!is.null(`path`)) {
        stopifnot(is.character(`path`), length(`path`) == 1)
        self$`path` <- `path`
      }
    },
    toJSON = function() {
      StorageKeyMetadataObject <- list()
      if (!is.null(self$`meta`)) {
        StorageKeyMetadataObject[['meta']] <-
          self$`meta`
      }
      if (!is.null(self$`url`)) {
        StorageKeyMetadataObject[['url']] <-
          self$`url`
      }
      if (!is.null(self$`name`)) {
        StorageKeyMetadataObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`type`)) {
        StorageKeyMetadataObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`path`)) {
        StorageKeyMetadataObject[['path']] <-
          self$`path`
      }

      StorageKeyMetadataObject
    },
    fromJSON = function(StorageKeyMetadataJson) {
      StorageKeyMetadataObject <- jsonlite::fromJSON(StorageKeyMetadataJson)
      if (!is.null(StorageKeyMetadataObject$`meta`)) {
        self$`meta` <- StorageKeyMetadataObject$`meta`
      }
      if (!is.null(StorageKeyMetadataObject$`url`)) {
        self$`url` <- StorageKeyMetadataObject$`url`
      }
      if (!is.null(StorageKeyMetadataObject$`name`)) {
        self$`name` <- StorageKeyMetadataObject$`name`
      }
      if (!is.null(StorageKeyMetadataObject$`type`)) {
        self$`type` <- StorageKeyMetadataObject$`type`
      }
      if (!is.null(StorageKeyMetadataObject$`path`)) {
        self$`path` <- StorageKeyMetadataObject$`path`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`meta`)) {
        sprintf(
        '"meta":
          "%s"
                ',
        self$`meta`
        )},
        if (!is.null(self$`url`)) {
        sprintf(
        '"url":
          "%s"
                ',
        self$`url`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )},
        if (!is.null(self$`path`)) {
        sprintf(
        '"path":
          "%s"
                ',
        self$`path`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StorageKeyMetadataJson) {
      StorageKeyMetadataObject <- jsonlite::fromJSON(StorageKeyMetadataJson)
      self$`meta` <- StorageKeyMetadataObject$`meta`
      self$`url` <- StorageKeyMetadataObject$`url`
      self$`name` <- StorageKeyMetadataObject$`name`
      self$`type` <- StorageKeyMetadataObject$`type`
      self$`path` <- StorageKeyMetadataObject$`path`
      self
    }
  )
)
