# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StorageKeyListResponse
#' @description StorageKeyListResponse Class
#' @format An \code{R6Class} generator object
#' @field resources  list( \link{StorageKeyMetadata} ) [optional]
#'
#' @field meta  object [optional]
#'
#' @field url  character [optional]
#'
#' @field type  character [optional]
#'
#' @field path  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StorageKeyListResponse <- R6::R6Class(
  'StorageKeyListResponse',
  public = list(
    `resources` = NULL,
    `meta` = NULL,
    `url` = NULL,
    `type` = NULL,
    `path` = NULL,
    initialize = function(`resources`=NULL, `meta`=NULL, `url`=NULL, `type`=NULL, `path`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`resources`)) {
        stopifnot(is.vector(`resources`))
        sapply(`resources`, function(x) stopifnot(R6::is.R6(x)))
        self$`resources` <- `resources`
      }
      if (!is.null(`meta`)) {
        self$`meta` <- `meta`
      }
      if (!is.null(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
        self$`url` <- `url`
      }
      if (!is.null(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!is.null(`path`)) {
        stopifnot(is.character(`path`), length(`path`) == 1)
        self$`path` <- `path`
      }
    },
    toJSON = function() {
      StorageKeyListResponseObject <- list()
      if (!is.null(self$`resources`)) {
        StorageKeyListResponseObject[['resources']] <-
          lapply(self$`resources`, function(x) x$toJSON())
      }
      if (!is.null(self$`meta`)) {
        StorageKeyListResponseObject[['meta']] <-
          self$`meta`
      }
      if (!is.null(self$`url`)) {
        StorageKeyListResponseObject[['url']] <-
          self$`url`
      }
      if (!is.null(self$`type`)) {
        StorageKeyListResponseObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`path`)) {
        StorageKeyListResponseObject[['path']] <-
          self$`path`
      }

      StorageKeyListResponseObject
    },
    fromJSON = function(StorageKeyListResponseJson) {
      StorageKeyListResponseObject <- jsonlite::fromJSON(StorageKeyListResponseJson)
      if (!is.null(StorageKeyListResponseObject$`resources`)) {
        self$`resources` <- ApiClient$new()$deserializeObj(StorageKeyListResponseObject$`resources`, "array[StorageKeyMetadata]", loadNamespace("olrundeck"))
      }
      if (!is.null(StorageKeyListResponseObject$`meta`)) {
        self$`meta` <- StorageKeyListResponseObject$`meta`
      }
      if (!is.null(StorageKeyListResponseObject$`url`)) {
        self$`url` <- StorageKeyListResponseObject$`url`
      }
      if (!is.null(StorageKeyListResponseObject$`type`)) {
        self$`type` <- StorageKeyListResponseObject$`type`
      }
      if (!is.null(StorageKeyListResponseObject$`path`)) {
        self$`path` <- StorageKeyListResponseObject$`path`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`resources`)) {
        sprintf(
        '"resources":
        [%s]
',
        paste(sapply(self$`resources`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`meta`)) {
        sprintf(
        '"meta":
          "%s"
                ',
        self$`meta`
        )},
        if (!is.null(self$`url`)) {
        sprintf(
        '"url":
          "%s"
                ',
        self$`url`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )},
        if (!is.null(self$`path`)) {
        sprintf(
        '"path":
          "%s"
                ',
        self$`path`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StorageKeyListResponseJson) {
      StorageKeyListResponseObject <- jsonlite::fromJSON(StorageKeyListResponseJson)
      self$`resources` <- ApiClient$new()$deserializeObj(StorageKeyListResponseObject$`resources`, "array[StorageKeyMetadata]", loadNamespace("olrundeck"))
      self$`meta` <- StorageKeyListResponseObject$`meta`
      self$`url` <- StorageKeyListResponseObject$`url`
      self$`type` <- StorageKeyListResponseObject$`type`
      self$`path` <- StorageKeyListResponseObject$`path`
      self
    }
  )
)
