# Rundeck
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title WorkflowStep
#' @description WorkflowStep Class
#' @format An \code{R6Class} generator object
#' @field jobref  object [optional]
#'
#' @field jobId  character [optional]
#'
#' @field description  character [optional]
#'
#' @field exec  character [optional]
#'
#' @field script  character [optional]
#'
#' @field scriptfile  character [optional]
#'
#' @field scripturl  character [optional]
#'
#' @field type  character [optional]
#'
#' @field nodeStep  character [optional]
#'
#' @field workflow  list( \link{WorkflowStep} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
WorkflowStep <- R6::R6Class(
  'WorkflowStep',
  public = list(
    `jobref` = NULL,
    `jobId` = NULL,
    `description` = NULL,
    `exec` = NULL,
    `script` = NULL,
    `scriptfile` = NULL,
    `scripturl` = NULL,
    `type` = NULL,
    `nodeStep` = NULL,
    `workflow` = NULL,
    initialize = function(`jobref`=NULL, `jobId`=NULL, `description`=NULL, `exec`=NULL, `script`=NULL, `scriptfile`=NULL, `scripturl`=NULL, `type`=NULL, `nodeStep`=NULL, `workflow`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`jobref`)) {
        self$`jobref` <- `jobref`
      }
      if (!is.null(`jobId`)) {
        stopifnot(is.character(`jobId`), length(`jobId`) == 1)
        self$`jobId` <- `jobId`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`exec`)) {
        stopifnot(is.character(`exec`), length(`exec`) == 1)
        self$`exec` <- `exec`
      }
      if (!is.null(`script`)) {
        stopifnot(is.character(`script`), length(`script`) == 1)
        self$`script` <- `script`
      }
      if (!is.null(`scriptfile`)) {
        stopifnot(is.character(`scriptfile`), length(`scriptfile`) == 1)
        self$`scriptfile` <- `scriptfile`
      }
      if (!is.null(`scripturl`)) {
        stopifnot(is.character(`scripturl`), length(`scripturl`) == 1)
        self$`scripturl` <- `scripturl`
      }
      if (!is.null(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!is.null(`nodeStep`)) {
        stopifnot(is.character(`nodeStep`), length(`nodeStep`) == 1)
        self$`nodeStep` <- `nodeStep`
      }
      if (!is.null(`workflow`)) {
        stopifnot(is.vector(`workflow`))
        sapply(`workflow`, function(x) stopifnot(R6::is.R6(x)))
        self$`workflow` <- `workflow`
      }
    },
    toJSON = function() {
      WorkflowStepObject <- list()
      if (!is.null(self$`jobref`)) {
        WorkflowStepObject[['jobref']] <-
          self$`jobref`
      }
      if (!is.null(self$`jobId`)) {
        WorkflowStepObject[['jobId']] <-
          self$`jobId`
      }
      if (!is.null(self$`description`)) {
        WorkflowStepObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`exec`)) {
        WorkflowStepObject[['exec']] <-
          self$`exec`
      }
      if (!is.null(self$`script`)) {
        WorkflowStepObject[['script']] <-
          self$`script`
      }
      if (!is.null(self$`scriptfile`)) {
        WorkflowStepObject[['scriptfile']] <-
          self$`scriptfile`
      }
      if (!is.null(self$`scripturl`)) {
        WorkflowStepObject[['scripturl']] <-
          self$`scripturl`
      }
      if (!is.null(self$`type`)) {
        WorkflowStepObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`nodeStep`)) {
        WorkflowStepObject[['nodeStep']] <-
          self$`nodeStep`
      }
      if (!is.null(self$`workflow`)) {
        WorkflowStepObject[['workflow']] <-
          lapply(self$`workflow`, function(x) x$toJSON())
      }

      WorkflowStepObject
    },
    fromJSON = function(WorkflowStepJson) {
      WorkflowStepObject <- jsonlite::fromJSON(WorkflowStepJson)
      if (!is.null(WorkflowStepObject$`jobref`)) {
        self$`jobref` <- WorkflowStepObject$`jobref`
      }
      if (!is.null(WorkflowStepObject$`jobId`)) {
        self$`jobId` <- WorkflowStepObject$`jobId`
      }
      if (!is.null(WorkflowStepObject$`description`)) {
        self$`description` <- WorkflowStepObject$`description`
      }
      if (!is.null(WorkflowStepObject$`exec`)) {
        self$`exec` <- WorkflowStepObject$`exec`
      }
      if (!is.null(WorkflowStepObject$`script`)) {
        self$`script` <- WorkflowStepObject$`script`
      }
      if (!is.null(WorkflowStepObject$`scriptfile`)) {
        self$`scriptfile` <- WorkflowStepObject$`scriptfile`
      }
      if (!is.null(WorkflowStepObject$`scripturl`)) {
        self$`scripturl` <- WorkflowStepObject$`scripturl`
      }
      if (!is.null(WorkflowStepObject$`type`)) {
        self$`type` <- WorkflowStepObject$`type`
      }
      if (!is.null(WorkflowStepObject$`nodeStep`)) {
        self$`nodeStep` <- WorkflowStepObject$`nodeStep`
      }
      if (!is.null(WorkflowStepObject$`workflow`)) {
        self$`workflow` <- ApiClient$new()$deserializeObj(WorkflowStepObject$`workflow`, "array[WorkflowStep]", loadNamespace("olrundeck"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`jobref`)) {
        sprintf(
        '"jobref":
          "%s"
                ',
        self$`jobref`
        )},
        if (!is.null(self$`jobId`)) {
        sprintf(
        '"jobId":
          "%s"
                ',
        self$`jobId`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`exec`)) {
        sprintf(
        '"exec":
          "%s"
                ',
        self$`exec`
        )},
        if (!is.null(self$`script`)) {
        sprintf(
        '"script":
          "%s"
                ',
        self$`script`
        )},
        if (!is.null(self$`scriptfile`)) {
        sprintf(
        '"scriptfile":
          "%s"
                ',
        self$`scriptfile`
        )},
        if (!is.null(self$`scripturl`)) {
        sprintf(
        '"scripturl":
          "%s"
                ',
        self$`scripturl`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          "%s"
                ',
        self$`type`
        )},
        if (!is.null(self$`nodeStep`)) {
        sprintf(
        '"nodeStep":
          "%s"
                ',
        self$`nodeStep`
        )},
        if (!is.null(self$`workflow`)) {
        sprintf(
        '"workflow":
        [%s]
',
        paste(sapply(self$`workflow`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(WorkflowStepJson) {
      WorkflowStepObject <- jsonlite::fromJSON(WorkflowStepJson)
      self$`jobref` <- WorkflowStepObject$`jobref`
      self$`jobId` <- WorkflowStepObject$`jobId`
      self$`description` <- WorkflowStepObject$`description`
      self$`exec` <- WorkflowStepObject$`exec`
      self$`script` <- WorkflowStepObject$`script`
      self$`scriptfile` <- WorkflowStepObject$`scriptfile`
      self$`scripturl` <- WorkflowStepObject$`scripturl`
      self$`type` <- WorkflowStepObject$`type`
      self$`nodeStep` <- WorkflowStepObject$`nodeStep`
      self$`workflow` <- ApiClient$new()$deserializeObj(WorkflowStepObject$`workflow`, "array[WorkflowStep]", loadNamespace("olrundeck"))
      self
    }
  )
)
