# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import olrundeck
from olrundeck.api.roles_api import RolesApi  # noqa: E501
from olrundeck.rest import ApiException


class TestRolesApi(unittest.TestCase):
    """RolesApi unit test stubs"""

    def setUp(self):
        self.api = olrundeck.api.roles_api.RolesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_role_list(self):
        """Test case for user_role_list

        List the roles of the authenticated user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
