# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import olrundeck
from olrundeck.api.schedule_api import ScheduleApi  # noqa: E501
from olrundeck.rest import ApiException


class TestScheduleApi(unittest.TestCase):
    """ScheduleApi unit test stubs"""

    def setUp(self):
        self.api = olrundeck.api.schedule_api.ScheduleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_job_schedule_bulk_disable(self):
        """Test case for job_schedule_bulk_disable

        Bulk disable job schedule  # noqa: E501
        """
        pass

    def test_job_schedule_bulk_enable(self):
        """Test case for job_schedule_bulk_enable

        Bulk enable job schedule  # noqa: E501
        """
        pass

    def test_job_schedule_disable(self):
        """Test case for job_schedule_disable

        Disable the schedule for a job. (ACL requires toggle_schedule action for a job.)  # noqa: E501
        """
        pass

    def test_job_schedule_enable(self):
        """Test case for job_schedule_enable

        Enable the schedule for a job. (ACL requires toggle_schedule action for a job.)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
