# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openlattice_rundeck
from openlattice_rundeck.api.job_api import JobApi  # noqa: E501
from openlattice_rundeck.rest import ApiException


class TestJobApi(unittest.TestCase):
    """JobApi unit test stubs"""

    def setUp(self):
        self.api = openlattice_rundeck.api.job_api.JobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_project_archive_import(self):
        """Test case for project_archive_import

        Import project archive.  # noqa: E501
        """
        pass

    def test_project_jobs_export(self):
        """Test case for project_jobs_export

        Export the job definitions in XML or YAML formats.  # noqa: E501
        """
        pass

    def test_project_jobs_import(self):
        """Test case for project_jobs_import

        Import job definitions in XML or YAML formats.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
