# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openlattice_rundeck
from openlattice_rundeck.api.metric_api import MetricApi  # noqa: E501
from openlattice_rundeck.rest import ApiException


class TestMetricApi(unittest.TestCase):
    """MetricApi unit test stubs"""

    def setUp(self):
        self.api = openlattice_rundeck.api.metric_api.MetricApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_metric_list(self):
        """Test case for metric_list

        List links to enabled Metrics endpoints  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
