# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import olrundeck
from olrundeck.models.inline_object10 import InlineObject10  # noqa: E501
from olrundeck.rest import ApiException

class TestInlineObject10(unittest.TestCase):
    """InlineObject10 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineObject10
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = olrundeck.models.inline_object10.InlineObject10()  # noqa: E501
        if include_optional :
            return InlineObject10(
                server = olrundeck.models._api_26_scheduler_takeover_server._api_26_scheduler_takeover_server(
                    uuid = '0', 
                    all = True, ), 
                project = '0', 
                job = olrundeck.models._api_26_scheduler_takeover_job._api_26_scheduler_takeover_job(
                    id = '0', )
            )
        else :
            return InlineObject10(
        )

    def testInlineObject10(self):
        """Test InlineObject10"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
