# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openlattice_rundeck
from openlattice_rundeck.api.bulk_api import BulkApi  # noqa: E501
from openlattice_rundeck.rest import ApiException


class TestBulkApi(unittest.TestCase):
    """BulkApi unit test stubs"""

    def setUp(self):
        self.api = openlattice_rundeck.api.bulk_api.BulkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_job_bulk_delete(self):
        """Test case for job_bulk_delete

        Delete multiple job definitions at once  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
