# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ModifyUserRequest")

model.instance <- ModifyUserRequest$new()

test_that("firstName", {
  # tests for the property `firstName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`firstName`, "EXPECTED_RESULT")
})

test_that("lastName", {
  # tests for the property `lastName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`lastName`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

