# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobReference")

model.instance <- JobReference$new()

test_that("href", {
  # tests for the property `href` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`href`, "EXPECTED_RESULT")
})

test_that("permalink", {
  # tests for the property `permalink` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`permalink`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("pervious-owner", {
  # tests for the property `pervious-owner` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pervious-owner`, "EXPECTED_RESULT")
})

