# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Job")

model.instance <- Job$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("group", {
  # tests for the property `group` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`group`, "EXPECTED_RESULT")
})

test_that("project", {
  # tests for the property `project` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`project`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("href", {
  # tests for the property `href` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`href`, "EXPECTED_RESULT")
})

test_that("permalink", {
  # tests for the property `permalink` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`permalink`, "EXPECTED_RESULT")
})

test_that("scheduled", {
  # tests for the property `scheduled` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`scheduled`, "EXPECTED_RESULT")
})

test_that("scheduleEnabled", {
  # tests for the property `scheduleEnabled` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`scheduleEnabled`, "EXPECTED_RESULT")
})

test_that("serverNodeUUID", {
  # tests for the property `serverNodeUUID` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`serverNodeUUID`, "EXPECTED_RESULT")
})

test_that("serverOwner", {
  # tests for the property `serverOwner` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`serverOwner`, "EXPECTED_RESULT")
})

test_that("enabled", {
  # tests for the property `enabled` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`enabled`, "EXPECTED_RESULT")
})

