# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StorageKeyMetadata")

model.instance <- StorageKeyMetadata$new()

test_that("meta", {
  # tests for the property `meta` (object)

  # uncomment below to test the property 
  #expect_equal(model.instance$`meta`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("path", {
  # tests for the property `path` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`path`, "EXPECTED_RESULT")
})

