# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject11")

model.instance <- InlineObject11$new()

test_that("contents", {
  # tests for the property `contents` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`contents`, "EXPECTED_RESULT")
})

