# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ExecuteJobRequest")

model.instance <- ExecuteJobRequest$new()

test_that("argString", {
  # tests for the property `argString` (character)
  # Argument string to pass to the job, of the form &#x60;-opt value -opt2 value ...&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`argString`, "EXPECTED_RESULT")
})

test_that("loglevel", {
  # tests for the property `loglevel` (character)
  # Loglevel to use

  # uncomment below to test the property 
  #expect_equal(model.instance$`loglevel`, "EXPECTED_RESULT")
})

test_that("asUser", {
  # tests for the property `asUser` (character)
  # A username identifying the user who ran the job. Requires &#x60;runAs&#x60; permission.

  # uncomment below to test the property 
  #expect_equal(model.instance$`asUser`, "EXPECTED_RESULT")
})

test_that("filter", {
  # tests for the property `filter` (character)
  # A node filter string.

  # uncomment below to test the property 
  #expect_equal(model.instance$`filter`, "EXPECTED_RESULT")
})

test_that("runAtTime", {
  # tests for the property `runAtTime` (character)
  # Specify a time to run the job (*API v18* or later). &#x60;ISO-8601&#x60; format with optional milliseconds.

  # uncomment below to test the property 
  #expect_equal(model.instance$`runAtTime`, "EXPECTED_RESULT")
})

test_that("options", {
  # tests for the property `options` (object)
  # Option value for option named &#x60;OPTNAME&#x60;. If specified the &#x60;argString&#x60; value is ignored (*API v18* or later).

  # uncomment below to test the property 
  #expect_equal(model.instance$`options`, "EXPECTED_RESULT")
})

