# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AclList")

model.instance <- AclList$new()

test_that("path", {
  # tests for the property `path` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`path`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("href", {
  # tests for the property `href` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`href`, "EXPECTED_RESULT")
})

test_that("resources", {
  # tests for the property `resources` (array[AclReference])

  # uncomment below to test the property 
  #expect_equal(model.instance$`resources`, "EXPECTED_RESULT")
})

