# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test IncompleteLogExecutions")

model.instance <- IncompleteLogExecutions$new()

test_that("total", {
  # tests for the property `total` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

test_that("max", {
  # tests for the property `max` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`max`, "EXPECTED_RESULT")
})

test_that("offset", {
  # tests for the property `offset` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`offset`, "EXPECTED_RESULT")
})

test_that("executions", {
  # tests for the property `executions` (array[IncompleteLogExecution])

  # uncomment below to test the property 
  #expect_equal(model.instance$`executions`, "EXPECTED_RESULT")
})

