# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject10")

model.instance <- InlineObject10$new()

test_that("server", {
  # tests for the property `server` (Api26SchedulerTakeoverServer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`server`, "EXPECTED_RESULT")
})

test_that("project", {
  # tests for the property `project` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`project`, "EXPECTED_RESULT")
})

test_that("job", {
  # tests for the property `job` (Api26SchedulerTakeoverJob)

  # uncomment below to test the property 
  #expect_equal(model.instance$`job`, "EXPECTED_RESULT")
})

