# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobInputFileInfo")

model.instance <- JobInputFileInfo$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("user", {
  # tests for the property `user` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`user`, "EXPECTED_RESULT")
})

test_that("fileState", {
  # tests for the property `fileState` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`fileState`, "EXPECTED_RESULT")
})

test_that("sha", {
  # tests for the property `sha` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`sha`, "EXPECTED_RESULT")
})

test_that("jobId", {
  # tests for the property `jobId` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`jobId`, "EXPECTED_RESULT")
})

test_that("dateCreated", {
  # tests for the property `dateCreated` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`dateCreated`, "EXPECTED_RESULT")
})

test_that("serverNodeUUID", {
  # tests for the property `serverNodeUUID` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`serverNodeUUID`, "EXPECTED_RESULT")
})

test_that("fileName", {
  # tests for the property `fileName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`fileName`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})

test_that("expirationDate", {
  # tests for the property `expirationDate` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`expirationDate`, "EXPECTED_RESULT")
})

test_that("execId", {
  # tests for the property `execId` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`execId`, "EXPECTED_RESULT")
})

