# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MetricApi")

api.instance <- MetricApi$new()

test_that("metric_list", {
  # tests for metric_list
  # base path: http://localhost
  # List links to enabled Metrics endpoints
  # @return [InlineResponse2001]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

