# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ProjectApi")

api.instance <- ProjectApi$new()

test_that("api26_project_project_motd_md_delete", {
  # tests for api26_project_project_motd_md_delete
  # base path: http://localhost
  # Delete project motd.md
  # @param character  project  Name of the project to import jobs into. 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

