# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TakeoverScheduleResponse")

model.instance <- TakeoverScheduleResponse$new()

test_that("takeoverSchedule", {
  # tests for the property `takeoverSchedule` (object)

  # uncomment below to test the property 
  #expect_equal(model.instance$`takeoverSchedule`, "EXPECTED_RESULT")
})

test_that("self", {
  # tests for the property `self` (object)

  # uncomment below to test the property 
  #expect_equal(model.instance$`self`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("apiversion", {
  # tests for the property `apiversion` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`apiversion`, "EXPECTED_RESULT")
})

test_that("success", {
  # tests for the property `success` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`success`, "EXPECTED_RESULT")
})

