# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StorageApi")

api.instance <- StorageApi$new()

test_that("api26_storage_keys_path_delete", {
  # tests for api26_storage_keys_path_delete
  # base path: http://localhost
  # Deletes the file if it exists and returns 204 response.
  # @param AnyType  path  Key path 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

