# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ExecutionOutput")

model.instance <- ExecutionOutput$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("offset", {
  # tests for the property `offset` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`offset`, "EXPECTED_RESULT")
})

test_that("completed", {
  # tests for the property `completed` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`completed`, "EXPECTED_RESULT")
})

test_that("execCompleted", {
  # tests for the property `execCompleted` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`execCompleted`, "EXPECTED_RESULT")
})

test_that("hasFailedNodes", {
  # tests for the property `hasFailedNodes` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`hasFailedNodes`, "EXPECTED_RESULT")
})

test_that("execState", {
  # tests for the property `execState` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`execState`, "EXPECTED_RESULT")
})

test_that("lastModified", {
  # tests for the property `lastModified` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`lastModified`, "EXPECTED_RESULT")
})

test_that("execDuration", {
  # tests for the property `execDuration` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`execDuration`, "EXPECTED_RESULT")
})

test_that("percentLoaded", {
  # tests for the property `percentLoaded` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`percentLoaded`, "EXPECTED_RESULT")
})

test_that("totalSize", {
  # tests for the property `totalSize` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`totalSize`, "EXPECTED_RESULT")
})

test_that("retryBackoff", {
  # tests for the property `retryBackoff` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`retryBackoff`, "EXPECTED_RESULT")
})

test_that("clusterExec", {
  # tests for the property `clusterExec` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`clusterExec`, "EXPECTED_RESULT")
})

test_that("compacted", {
  # tests for the property `compacted` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`compacted`, "EXPECTED_RESULT")
})

test_that("entries", {
  # tests for the property `entries` (array[ExecutionOutputEntry])

  # uncomment below to test the property 
  #expect_equal(model.instance$`entries`, "EXPECTED_RESULT")
})

