# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject")

model.instance <- InlineObject$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("config", {
  # tests for the property `config` (object)

  # uncomment below to test the property 
  #expect_equal(model.instance$`config`, "EXPECTED_RESULT")
})

