# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobInputFileListResponse")

model.instance <- JobInputFileListResponse$new()

test_that("paging", {
  # tests for the property `paging` (Paging)

  # uncomment below to test the property 
  #expect_equal(model.instance$`paging`, "EXPECTED_RESULT")
})

test_that("files", {
  # tests for the property `files` (array[JobInputFileInfo])

  # uncomment below to test the property 
  #expect_equal(model.instance$`files`, "EXPECTED_RESULT")
})

