# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineObject1")

model.instance <- InlineObject1$new()

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

