# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ClusterApi")

api.instance <- ClusterApi$new()

test_that("system_scheduled_jobs_for_server", {
  # tests for system_scheduled_jobs_for_server
  # base path: http://localhost
  # List the scheduled Jobs with their schedule owned by the cluster server with the specified UUID
  # @param character  uuid  The ID of the user to retrieve profile information for 
  # @return [array[Job]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("system_scheduled_jobs_list", {
  # tests for system_scheduled_jobs_list
  # base path: http://localhost
  # List the scheduled Jobs with their schedule owned by the cluster server
  # @return [array[Job]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("system_scheduler_takeover", {
  # tests for system_scheduler_takeover
  # base path: http://localhost
  # Tell a Rundeck server in cluster mode to claim all scheduled jobs from another cluster server
  # @param InlineObject10  inline_object10   
  # @return [TakeoverScheduleResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

