# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BulkJobFailedInfo")

model.instance <- BulkJobFailedInfo$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("errorCode", {
  # tests for the property `errorCode` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`errorCode`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

