# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ExecutionOutputEntry")

model.instance <- ExecutionOutputEntry$new()

test_that("time", {
  # tests for the property `time` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`time`, "EXPECTED_RESULT")
})

test_that("absolute_time", {
  # tests for the property `absolute_time` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`absolute_time`, "EXPECTED_RESULT")
})

test_that("log", {
  # tests for the property `log` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`log`, "EXPECTED_RESULT")
})

test_that("level", {
  # tests for the property `level` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`level`, "EXPECTED_RESULT")
})

test_that("stepctx", {
  # tests for the property `stepctx` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`stepctx`, "EXPECTED_RESULT")
})

test_that("node", {
  # tests for the property `node` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`node`, "EXPECTED_RESULT")
})

