# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LogApi")

api.instance <- LogApi$new()

test_that("system_incomplete_log_storage_executions_get", {
  # tests for system_incomplete_log_storage_executions_get
  # base path: http://localhost
  # List all executions with incomplete log storage
  # @return [IncompleteLogExecutions]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("system_incomplete_log_storage_executions_resume", {
  # tests for system_incomplete_log_storage_executions_resume
  # base path: http://localhost
  # Resume processing incomplete Log Storage uploads
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("system_log_storage_info_get", {
  # tests for system_log_storage_info_get
  # base path: http://localhost
  # Get Log Storage information and stats
  # @return [LogStorage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

