# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Paging")

model.instance <- Paging$new()

test_that("count", {
  # tests for the property `count` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`count`, "EXPECTED_RESULT")
})

test_that("total", {
  # tests for the property `total` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

test_that("offset", {
  # tests for the property `offset` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`offset`, "EXPECTED_RESULT")
})

test_that("max", {
  # tests for the property `max` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`max`, "EXPECTED_RESULT")
})

