# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BulkApi")

api.instance <- BulkApi$new()

test_that("job_bulk_delete", {
  # tests for job_bulk_delete
  # base path: http://localhost
  # Delete multiple job definitions at once
  # @param InlineObject1  inline_object1   
  # @return [JobBulkOperationResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

