# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StorageKeyMetaType")

model.instance <- StorageKeyMetaType$new()

