# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AclPolicyResponse")

model.instance <- AclPolicyResponse$new()

test_that("contents", {
  # tests for the property `contents` (character)
  # Policy as JSON encoded YAML string

  # uncomment below to test the property 
  #expect_equal(model.instance$`contents`, "EXPECTED_RESULT")
})

