# coding: utf-8

"""
    Rundeck

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from openlattice_rundeck.api_client import ApiClient
from openlattice_rundeck.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class JobApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def project_archive_import(self, project, body, **kwargs):  # noqa: E501
        """Import project archive.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.project_archive_import(project, body, async_req=True)
        >>> result = thread.get()

        :param project: Name of the project to import jobs into. (required)
        :type project: str
        :param body: (required)
        :type body: object
        :param job_uuid_option:
        :type job_uuid_option: object
        :param import_executions:
        :type import_executions: bool
        :param import_config:
        :type import_config: bool
        :param import_acl:
        :type import_acl: bool
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """
        kwargs['_return_http_data_only'] = True
        return self.project_archive_import_with_http_info(project, body, **kwargs)  # noqa: E501

    def project_archive_import_with_http_info(self, project, body, **kwargs):  # noqa: E501
        """Import project archive.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.project_archive_import_with_http_info(project, body, async_req=True)
        >>> result = thread.get()

        :param project: Name of the project to import jobs into. (required)
        :type project: str
        :param body: (required)
        :type body: object
        :param job_uuid_option:
        :type job_uuid_option: object
        :param import_executions:
        :type import_executions: bool
        :param import_config:
        :type import_config: bool
        :param import_acl:
        :type import_acl: bool
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """

        local_var_params = locals()

        all_params = [
            'project',
            'body',
            'job_uuid_option',
            'import_executions',
            'import_config',
            'import_acl'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method project_archive_import" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'project' is set
        if self.api_client.client_side_validation and ('project' not in local_var_params or  # noqa: E501
                                                        local_var_params['project'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `project` when calling `project_archive_import`")  # noqa: E501
        # verify the required parameter 'body' is set
        if self.api_client.client_side_validation and ('body' not in local_var_params or  # noqa: E501
                                                        local_var_params['body'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `body` when calling `project_archive_import`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project' in local_var_params:
            path_params['project'] = local_var_params['project']  # noqa: E501

        query_params = []
        if 'job_uuid_option' in local_var_params and local_var_params['job_uuid_option'] is not None:  # noqa: E501
            query_params.append(('jobUuidOption', local_var_params['job_uuid_option']))  # noqa: E501
        if 'import_executions' in local_var_params and local_var_params['import_executions'] is not None:  # noqa: E501
            query_params.append(('importExecutions', local_var_params['import_executions']))  # noqa: E501
        if 'import_config' in local_var_params and local_var_params['import_config'] is not None:  # noqa: E501
            query_params.append(('importConfig', local_var_params['import_config']))  # noqa: E501
        if 'import_acl' in local_var_params and local_var_params['import_acl'] is not None:  # noqa: E501
            query_params.append(('importACL', local_var_params['import_acl']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in local_var_params:
            body_params = local_var_params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['rundeck_auth']  # noqa: E501

        return self.api_client.call_api(
            '/api/26/project/{project}/import', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))

    def project_jobs_export(self, project, **kwargs):  # noqa: E501
        """Export the job definitions in XML or YAML formats.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.project_jobs_export(project, async_req=True)
        >>> result = thread.get()

        :param project: The project to export jobs for. (required)
        :type project: str
        :param format: XML or YAML format for exported jobs.
        :type format: object
        :param idlist: A comma-separated list of Job IDs to export.
        :type idlist: str
        :param group_path: Group or partial group path to include all jobs within that group path.
        :type group_path: str
        :param job_filter: Filter for the job Name.
        :type job_filter: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: str
        """
        kwargs['_return_http_data_only'] = True
        return self.project_jobs_export_with_http_info(project, **kwargs)  # noqa: E501

    def project_jobs_export_with_http_info(self, project, **kwargs):  # noqa: E501
        """Export the job definitions in XML or YAML formats.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.project_jobs_export_with_http_info(project, async_req=True)
        >>> result = thread.get()

        :param project: The project to export jobs for. (required)
        :type project: str
        :param format: XML or YAML format for exported jobs.
        :type format: object
        :param idlist: A comma-separated list of Job IDs to export.
        :type idlist: str
        :param group_path: Group or partial group path to include all jobs within that group path.
        :type group_path: str
        :param job_filter: Filter for the job Name.
        :type job_filter: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(str, status_code(int), headers(HTTPHeaderDict))
        """

        local_var_params = locals()

        all_params = [
            'project',
            'format',
            'idlist',
            'group_path',
            'job_filter'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method project_jobs_export" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'project' is set
        if self.api_client.client_side_validation and ('project' not in local_var_params or  # noqa: E501
                                                        local_var_params['project'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `project` when calling `project_jobs_export`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project' in local_var_params:
            path_params['project'] = local_var_params['project']  # noqa: E501

        query_params = []
        if 'format' in local_var_params and local_var_params['format'] is not None:  # noqa: E501
            query_params.append(('format', local_var_params['format']))  # noqa: E501
        if 'idlist' in local_var_params and local_var_params['idlist'] is not None:  # noqa: E501
            query_params.append(('idlist', local_var_params['idlist']))  # noqa: E501
        if 'group_path' in local_var_params and local_var_params['group_path'] is not None:  # noqa: E501
            query_params.append(('groupPath', local_var_params['group_path']))  # noqa: E501
        if 'job_filter' in local_var_params and local_var_params['job_filter'] is not None:  # noqa: E501
            query_params.append(('jobFilter', local_var_params['job_filter']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['rundeck_auth']  # noqa: E501

        return self.api_client.call_api(
            '/api/26/project/{project}/jobs/export', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))

    def project_jobs_import(self, project, body, **kwargs):  # noqa: E501
        """Import job definitions in XML or YAML formats.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.project_jobs_import(project, body, async_req=True)
        >>> result = thread.get()

        :param project: Name of the project to import jobs into. (required)
        :type project: str
        :param body: (required)
        :type body: object
        :param content_type:
        :type content_type: object
        :param accept:
        :type accept: object
        :param file_format:
        :type file_format: object
        :param dupe_option:
        :type dupe_option: object
        :param uuid_option:
        :type uuid_option: object
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: object
        """
        kwargs['_return_http_data_only'] = True
        return self.project_jobs_import_with_http_info(project, body, **kwargs)  # noqa: E501

    def project_jobs_import_with_http_info(self, project, body, **kwargs):  # noqa: E501
        """Import job definitions in XML or YAML formats.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.project_jobs_import_with_http_info(project, body, async_req=True)
        >>> result = thread.get()

        :param project: Name of the project to import jobs into. (required)
        :type project: str
        :param body: (required)
        :type body: object
        :param content_type:
        :type content_type: object
        :param accept:
        :type accept: object
        :param file_format:
        :type file_format: object
        :param dupe_option:
        :type dupe_option: object
        :param uuid_option:
        :type uuid_option: object
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _return_http_data_only: response data without head status code
                                       and headers
        :type _return_http_data_only: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(object, status_code(int), headers(HTTPHeaderDict))
        """

        local_var_params = locals()

        all_params = [
            'project',
            'body',
            'content_type',
            'accept',
            'file_format',
            'dupe_option',
            'uuid_option'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method project_jobs_import" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'project' is set
        if self.api_client.client_side_validation and ('project' not in local_var_params or  # noqa: E501
                                                        local_var_params['project'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `project` when calling `project_jobs_import`")  # noqa: E501
        # verify the required parameter 'body' is set
        if self.api_client.client_side_validation and ('body' not in local_var_params or  # noqa: E501
                                                        local_var_params['body'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `body` when calling `project_jobs_import`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project' in local_var_params:
            path_params['project'] = local_var_params['project']  # noqa: E501

        query_params = []
        if 'file_format' in local_var_params and local_var_params['file_format'] is not None:  # noqa: E501
            query_params.append(('fileFormat', local_var_params['file_format']))  # noqa: E501
        if 'dupe_option' in local_var_params and local_var_params['dupe_option'] is not None:  # noqa: E501
            query_params.append(('dupeOption', local_var_params['dupe_option']))  # noqa: E501
        if 'uuid_option' in local_var_params and local_var_params['uuid_option'] is not None:  # noqa: E501
            query_params.append(('uuidOption', local_var_params['uuid_option']))  # noqa: E501

        header_params = {}
        if 'content_type' in local_var_params:
            header_params['content-type'] = local_var_params['content_type']  # noqa: E501
        if 'accept' in local_var_params:
            header_params['accept'] = local_var_params['accept']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in local_var_params:
            body_params = local_var_params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['rundeck_auth']  # noqa: E501

        return self.api_client.call_api(
            '/api/26/project/{project}/jobs/import', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats,
            _request_auth=local_var_params.get('_request_auth'))
